<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 2 capability(ies) for X-82.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-82/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'G17-10' => 'the $99.99/$179.99 figures are DEAD (P-001 · T468 — two packages, prices never change, numbers live in the registry).  Grandfathering survives exactly as R118 states it',

    // status: SPECCED
    'G17-26' => 'rollover-or-expire is a rate-registry policy the owner sets;  the metering model of record has auto top-up universal and nothing stopping at zero',
];
