<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 13 capability(ies) for X-103.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-103/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'G6-11' => 'device routing on the short-linker (P-072)',

    // status: SPECCED
    'G6-15' => 'the header\'s first line',

    // status: SPECCED
    'G6-16' => 'named in the header;  the "10% off" is the tenant\'s offer, never ours (T591)',

    // status: SPECCED
    'G6-17' => 'named in the header; rendered by X-194',

    // status: SPECCED
    'G6-20' => 'named in the header; a marketplace app is a MANIFEST, never injected code (X-195)',

    // status: SPECCED
    'G6-27' => 'named in the header; the PIN rides C-Sms',

    // status: SPECCED
    'G6-32' => 'named in the header; the invoice is X-199\'s',

    // status: SPECCED
    'G7-16' => 'custom slugs on the short-linker (P-072)',

    // status: SPECCED
    'G7-18' => 'named in the header; the review gateway subdomain is C-Reviews\'',

    // status: SPECCED
    'G9-04' => 'the full-stack site law — pixel on every site by construction',

    // status: SPECCED
    'G12-39' => 'the review widget on the site; the plugin path is X-104\'s',

    // status: SPECCED
    'G16-07' => 'an expiring short link (P-072)',

    // status: SPECCED
    'G19-07' => 'expiring and click-capped short links',
];
