<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 6 capability(ies) for X-201.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-201/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'G1-08' => 'own table `disputes` · own events `dispute.opened/evidence.compiled/resolved` · operator queue UI — passes all three tests, no parent exists. ⛔ "instantly suspends" must ride **R83 · transcribed from the G1 audit 2026-08-27',

    // status:
    'N-007' => 'refuses: the evidence bundle assembles itself; call logs, transcripts, signatures, delivery receipts, the invoice AND the consent record — asserted present before submission',

    // status:
    'N-008' => 'refuses: it accepts chargeback.received from any gateway; doctor asserts no gateway name appears in the dispute logic (P-197)',

    // status:
    'N-009' => 'refuses: the exposure ledger; money taken vs work DELIVERED, per tenant',

    // status:
    'N-010' => 'refuses: the verb does not exist here; a dispute is defended or conceded; money back is X-198\'s and it is L1',

    // status:
    'N-011' => 'refuses: deadlines are a clock, not a hope; a dispute inside 48h of its deadline RAISES to a human regardless of state',
];
