<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 10 capability(ies) for X-141.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-141/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'N-141-01' => '',

    // status: SPECCED
    'N-078' => '',

    // status: SPECCED
    'N-079' => '',

    // status: SPECCED
    'N-080' => '',

    // status: SPECCED
    'N-063' => '',

    // status: SPECCED
    'N-064' => '',

    // status: SPECCED
    'N-067' => '',

    // status: SPECCED
    'N-073' => '',

    // status: SPECCED
    'N-076' => '',

    // status: SPECCED
    'N-085' => '',
];
