<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 7 capability(ies) for X-104.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-104/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'G3-60' => 'NAME COLLISION — X-109\'s header also claims "the universal form hijacker"; the description here is the tenant\'s OWN WordPress site. C4 draws the line',

    // status: SPECCED
    'G6-26' => 'named in the header',

    // status: SPECCED
    'G6-34' => 'named in the header',

    // status: SPECCED
    'G6-35' => 'the takeover path is named;  it runs on the tenant\'s OWN site with their key — the name is the register\'s, not ours',

    // status: SPECCED
    'G7-46' => 'the plugin wears the agency\'s name',

    // status: SPECCED
    'G8-38' => 'named in the header',

    // status: SPECCED
    'G19-16' => 'named in the header',
];
