<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 44 capability(ies) for X-204.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-204/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'G1-11' => 'refuses: X-128\'s matrix regenerates with zero orphans and lists exactly three subscribers on invoice.paid, asserted at the wave gate; ⑥⑦ none — it is a seam',

    // status: SPECCED
    'G1-22' => 'refuses: the subscribe list is generated from @emits across the roster, so an unemittable event cannot be chosen · the screen is X-142\'s (F-11); ⑥ tenant-facing on X-142 · ⑦ none',

    // status: SPECCED
    'G1-41' => 'refuses: the test passes against a body the real event never sends; the sample is generated from the same serializer as the live event, asserted by diffing the two',

    // status: SPECCED
    'G2-52' => 'the outbound payload map on the broker',

    // status: SPECCED
    'G4-02' => 'token.issue · token.revoke, tenant-scoped',

    // status: SPECCED
    'G4-03' => 'every invocation logged with timestamp, IP + geo, user and actor_type',

    // status: SPECCED
    'G4-10' => 'named in the header — 10 consecutive failures, tenant emailed · refuses: retrying after 10 consecutive failures',

    // status: SPECCED
    'G4-12' => 'Redis on high-read nouns, invalidated inline on write',

    // status: SPECCED
    'G4-16' => 'RLS FORCEd on every noun table, never optional',

    // status: SPECCED
    'G4-17' => 'Horizon scales on queue depth',

    // status: SPECCED
    'G4-18' => 'tenant-scoped, permission-inherited tokens',

    // status: SPECCED
    'G4-21' => 'read-replica routing at the entity layer; the topology is turn 95\'s',

    // status: SPECCED
    'G4-32' => 'queue the spike, never drop it',

    // status: SPECCED
    'G4-34' => '1 · 5 · 30 min',

    // status: SPECCED
    'G4-37' => 'Asset versioning; the ransomware case is turn 93\'s',

    // status: SPECCED
    'G4-42' => 'version restore with a compensable reversal class',

    // status: SPECCED
    'G4-43' => 'global retries on every outbound call',

    // status: SPECCED
    'G4-46' => 'Asset history and side-by-side compare',

    // status: SPECCED
    'G4-48' => 'named in the header',

    // status: SPECCED
    'G4-50' => 'they ride the same catalogue; the catalogue is X-122\'s',

    // status: SPECCED
    'G4-51' => 'expand/contract on the noun tables; the release switch is Step 8\'s',

    // status: SPECCED
    'G7-26' => 'RabbitMQ/SQS is corpus vocabulary — Horizon + Redis (§22)',

    // status: SPECCED
    'G10-07' => 'refuses: ConsentService; the registers are provider slots, DEFAULT OFF, the tenant\'s own credentials (P-066) — see §166.5',

    // status: SPECCED
    'G10-12' => 'refuses: ConsentService; the permit as an immutable provenance record; an import is not consent (P-069)',

    // status: SPECCED
    'G10-14' => 'every invocation is already immutably logged',

    // status: SPECCED
    'G10-17' => 'refuses: ConsentService; = Automated TCPA Scrubbing; one spec',

    // status: SPECCED
    'G10-18' => 'the middleware every send passes through; P-060\'s 20 refusal reasons are the entire set',

    // status: SPECCED
    'G10-21' => 'append-only action log;  QLDB is corpus vocabulary — one database (§22)',

    // status: SPECCED
    'G10-33' => 'refuses: ConsentService; = Automated TCPA Scrubbing; one spec',

    // status: SPECCED
    'G10-35' => 'HMAC-SHA256 on every outbound webhook is named in the header · refuses: an outbound webhook without HMAC-SHA256',

    // status: SPECCED
    'G10-41' => 'per-tenant HMAC secret on the outbound payload · refuses: an outbound payload without the per-tenant HMAC secret',

    // status: SPECCED
    'G11-14' => 'named in the header — with version restore',

    // status: SPECCED
    'G11-26' => 'strict JSON-schema validation; a missing field is refused, never defaulted',

    // status: SPECCED
    'G17-16' => 'every invocation logs IP + MaxMind geo — named in the header',

    // status: SPECCED
    'G17-28' => 'field-level history with version restore — named in the header',

    // status: SPECCED
    'G21-06' => 'an outbound webhook destination;  the ad-fatigue trigger behind this example is FENCED (§44)',

    // status: SPECCED
    'G21-09' => 'a channel created by webhook on a project event',

    // status: SPECCED
    'G21-12' => 'a comment event pinging the right person',

    // status:
    'N-001' => 'a refusal without one of P-060\'s twenty codes FAILS THE BUILD',

    // status:
    'N-002' => 'refuses: every sender asks; no sender decides; grep finds no channel module deciding permission for itself',

    // status:
    'N-003' => 'refuses: STOP is instant and absolute; a STOP received mid-sequence halts every pending step for that Person within one cycle',

    // status:
    'N-004' => 'refuses: an imported Person is UNPERMITTED; (P-203) — asserted on X-212\'s commit',

    // status:
    'N-005' => 'refuses: the cadence ceiling counts every class; one person, one cadence — a GROW and an INFORM in the same window both count',

    // status:
    'N-006' => 'a hard bounce on one address never silences a person everywhere',
];
