<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 13 capability(ies) for X-186.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-186/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'G2-14' => 'best send time from the tenant\'s own history; still Marketing class, still inside the window (P-063)',

    // status: SPECCED
    'G3-53' => 'personalisation at scale;  "mathematically impossible to filter" is not a claim we make (P-120)',

    // status: SPECCED
    'G5-12' => 'still one mixed campaign (P-074)',

    // status: SPECCED
    'G5-14' => 'the Zapier/Sheets hop is corpus vocabulary; ours is native (X-123)',

    // status: SPECCED
    'G10-25' => 'scrubbed against suppression fresh as of each send',

    // status: SPECCED
    'G11-02' => 'named in the header',

    // status: SPECCED
    'G11-24' => 'named in the header;  every send from there is Marketing class from the CALLER',

    // status: SPECCED
    'G11-28' => 'named in the header — any reply stops the sequence (P-075)',

    // status: SPECCED
    'G11-31' => 'named in the header; still inside the marketing window (P-063)',

    // status: SPECCED
    'G12-18' => 'blocks swap on the Person\'s own tags',

    // status: SPECCED
    'G12-28' => 'a won deal stops the sequence (P-075);  the ad-audience purge half is FENCED (§44)',

    // status: SPECCED
    'G17-20' => 'a download drops into a sequence; the lane is declared, ConsentService decides',

    // status: SPECCED
    'G19-04' => 'multi-day sequences; any reply stops them (P-075)',
];
