<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 12 capability(ies) for X-186.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-186/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'G2-14' => 'refuses to schedule a campaign send time outside the tenant\'s permitted marketing window, even if the ML model identifies a better time.',

    // status: SPECCED
    'G5-12' => 'still one mixed campaign (P-074)',

    // status: SPECCED
    'G5-14' => 'the Zapier/Sheets hop is corpus vocabulary; ours is native (X-123)',

    // status: SPECCED
    'G10-25' => 'refuses to send to any contact that appears on the global suppression list refreshed at the exact moment of dispatch.',

    // status: SPECCED
    'G11-02' => 'refuses to auto-resend to unopens if the original dispatch occurred less than 24 hours prior, preventing spam complaints.',

    // status: SPECCED
    'G11-24' => 'refuses to dispatch omnichannel messages if the underlying channel lacks an opt-in for marketing class communications.',

    // status: SPECCED
    'G11-28' => 'named in the header — any reply stops the sequence (P-075)',

    // status: SPECCED
    'G11-31' => 'refuses to optimize send times beyond the legal 8 AM to 8 PM local window of the recipient.',

    // status: SPECCED
    'G12-18' => 'blocks swap on the Person\'s own tags',

    // status: SPECCED
    'G12-28' => 'refuses to keep a contact in the sequence if they match a won deal condition, immediately purging them from the audience.',

    // status: SPECCED
    'G17-20' => 'a download drops into a sequence; the lane is declared, ConsentService decides',

    // status: SPECCED
    'G19-04' => 'multi-day sequences; any reply stops them (P-075)',
];
