<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by \`module:scaffold\` from the documented header. DO NOT EDIT.
 *
 * A hand-edited manifest is a manifest that drifts, and every stale-record
 * defect in this programme was a hand-maintained file. Change the header,
 * re-run the scaffold.
 *
 * @module X-186
 * @intent GROW under §227.2
         * @scheduled campaign.scheduled <minutely> @owner X-186
 */
return [
    'module' => 'X-186',
    'intent' => 'GROW under §227.2',

    // ⛔⛔⛔ R235 — `ships` EQUALS `ceiling`. THE AUTOPILOT IS ON.
    //
    // This comment used to teach §227.2's intent default: "GROW ships
    // L1, PROPOSES ONLY, ALWAYS". The owner struck it — "ALL AI ON, by
    // my law. The client can turn it off if they want."
    //
    // ⭐ There is nothing to earn. @intent still DESCRIBES the action;
    //   it no longer gates when the action may run.
    'ships' => 'L2',
    'ceiling' => 'L2',

    'provides' => [
        'campaign.create',
        'campaign.run',
        'sequence.stop',
    ],
    'emits' => [
        'campaign.scheduled',
        'campaign.sent',
        'campaign.replied',
        'sequence.stopped',
        'campaign.exhausted',
    ],
    'consumes' => [
        'suppression.added',
        'capability.decided',
    ],

    // ⛔ P-163 — @owns_table may not name one of X-121's canonical nouns.
    'owns_table' => [
        'campaign_steps',
        'campaign_runs',
    ],
    'reads_table' => [],

    'renders' => [
        'sequence_builder',
        'audience_preview_count',
        'live_run',
        'stop_log',
    ],

    // P-209 — silence fails OPEN. `none` is a decision; absence is not.
    'agent_reachable' => [
        'none',
        'none',
        'none',
    ],
];
