<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 16 capability(ies) for X-113.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-113/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'G2-15' => 'overlapping time-off requests',

    // status: SPECCED
    'G2-28' => 'named in the header',

    // status: SPECCED
    'G2-44' => 'a wellbeing alert to a manager',

    // status: SPECCED
    'G4-15' => 'named in the header',

    // status: SPECCED
    'G4-35' => 'named in the header',

    // status: SPECCED
    'G7-29' => 'the review\'s hard numbers — but §150.4\'s scorecard is POSITIVE ONLY (T677)',

    // status: SPECCED
    'G9-36' => 'interview scorecards — hiring, not the platform',

    // status: SPECCED
    'G10-11' => 'mandatory-training reminders',

    // status: SPECCED
    'G10-15' => 'employee documents under RBAC',

    // status: SPECCED
    'G11-04' => 'new-hire provisioning',

    // status: SPECCED
    'G15-02' => 'T677: coaching and positive capability tracking only (§150.4)',

    // status: SPECCED
    'G15-04' => 'an account-class notification (P-062)',

    // status: SPECCED
    'G15-05' => 'T677 — coaching framing; the quarterly nag is a reminder, not a ranking',

    // status: SPECCED
    'G17-03' => 'hardware tied to a staff Person',

    // status: SPECCED
    'G20-02' => 'nagging managers about performance reviews — not customer reviews',

    // status: SPECCED
    'G21-08' => '/pto — the time-off workflow, not a platform decision',
];
