<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 8 capability(ies) for X-194.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-194/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'G4-20' => 'a house standard enforced by lint, not a capability row',

    // status: SPECCED
    'G8-10' => 'named in the header; the JSONB column is X-121\'s',

    // status: SPECCED
    'G9-11' => 'named in the header',

    // status: SPECCED
    'G9-23' => 'named in the header',

    // status: SPECCED
    'G9-26' => 'named in the header (report.pdf)',

    // status: SPECCED
    'G9-35' => 'counts and estimates never blend; the estimate tile stays violet-dashed until job value is entered',

    // status: SPECCED
    'G9-37' => 'a report renders in the location\'s own timezone',

    // status: SPECCED
    'G13-17' => 'revenue on the territory map; the polygons are X-10\'s',
];
