<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 5 capability(ies) for X-164.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-164/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'G10-01' => 'the customer signature freezes the version it was sold at;  F-19 — a contract that is not an estimate has no home',

    // status: SPECCED
    'G10-05' => 'the countersign step; see F-19',

    // status: SPECCED
    'G10-20' => 'the executed document linked to the record; see F-19',

    // status: SPECCED
    'G10-39' => 'CRM variables into a template; see F-19',

    // status: SPECCED
    'G17-11' => 'a quote expires at the version it was sold at',
];
