<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 5 capability(ies) for X-190.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-190/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'G7-25' => 'customer referral links;  "20% off" is the TENANT\'s offer under R26, never ours',

    // status: SPECCED
    'G7-43' => 'every customer gets a referral link; the short-linker is P-072',

    // status: SPECCED
    'G9-24' => 'named in the header',

    // status: SPECCED
    'G12-01' => 'named in the header',

    // status: SPECCED
    'G12-33' => 'named in the header;  the toast states a real event or does not fire (P-120)',
];
