<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 9 capability(ies) for X-150.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-150/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'N-050' => 'refuses NO_FACT',

    // status: SPECCED
    'N-051' => 'refuses NO_FACT',

    // status: SPECCED
    'N-054' => 'refuses NO_FACT',

    // status: SPECCED
    'N-056' => 'it stops at the first VALID SHAPE, never the first 200 · a provider that returns a wrong shape is DEMOTED, not retried · cost order is a config row',

    // status: SPECCED
    'N-057' => 'refuses NO_FACT',

    // status: SPECCED
    'N-058' => 'it stops at the first VALID SHAPE, never the first 200 · a provider that returns a wrong shape is DEMOTED, not retried · cost order is a config row',

    // status: SPECCED
    'N-060' => 'refuses NO_FACT',

    // status: SPECCED
    'N-150-01' => '⭐⭐ a phone field of N/A from tier 1 is REJECTED and tier 2 is called — a junk value that satisfies NOT NULL is the expensive failure',

    // status: SPECCED
    'N-150-02' => 'the expensive tier\'s call count over a month is bounded and asserted',
];
