<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 13 capability(ies) for X-07.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-07/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'G1-36' => 'booked and COLLECTED are asserted distinct, never summed',

    // status: SPECCED
    'G1-46' => 'booked and COLLECTED are asserted distinct, never summed',

    // status: SPECCED
    'G1-47' => 'booked and COLLECTED are asserted distinct, never summed',

    // status: SPECCED
    'G2-56' => 'named in the header refuses',

    // status: SPECCED
    'G2-59' => 'a tile over the forecast',

    // status: SPECCED
    'G2-66' => 'named in the header',

    // status: SPECCED
    'G2-68' => 'named in the header',

    // status: SPECCED
    'G9-27' => 'the monthly forecast; rendered by X-194',

    // status: SPECCED
    'G9-39' => 'T677 (owner) · §150.4 — burnout scoring as surveillance; the metric survives in G15 as a coaching signal only',

    // status: SPECCED
    'G9-40' => 'T677 (owner) · §150.4 — "proving tired reps lose the company money" is the punitive framing the ruling strikes',

    // status: SPECCED
    'G10-04' => 'it scores the DEAL, not the rep — sandbagging detection is named in the header',

    // status: SPECCED
    'G17-19' => 'named in the header',

    // status: SPECCED
    'G9-42' => '',
];
