<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 16 capability(ies) for X-191.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-191/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'G3-13' => 'named in the header',

    // status: SPECCED
    'G3-61' => 'named in the header',

    // status: SPECCED
    'G3-62' => '= G3-61; one spec',

    // status: SPECCED
    'G4-19' => 'named in the header',

    // status: SPECCED
    'G8-05' => 'named in the header',

    // status: SPECCED
    'G8-06' => '= the row above; one spec',

    // status: SPECCED
    'G8-11' => 'named in the header',

    // status: SPECCED
    'G8-20' => 'named in the header — one follow-up only',

    // status: SPECCED
    'G8-21' => '= the row above; one spec',

    // status: SPECCED
    'G8-34' => 'placement monitoring is named in the header',

    // status: SPECCED
    'G11-34' => 'the guest-post pitch that names something TRUE about the page',

    // status: SPECCED
    'G12-07' => 'ONE follow-up only, per the header — not three',

    // status: SPECCED
    'G12-14' => 'named in the header',

    // status: SPECCED
    'G12-15' => 'a yes from the editor drafts through X-183\'s gate',

    // status: SPECCED
    'G17-06' => '= G12-07; one spec, and  one follow-up only',

    // status: SPECCED
    'G17-09' => 'named in the header',
];
