<?php
$file = 'app/app/Console/Commands/ModuleScaffoldCommand.php';
$content = file_get_contents($file);

// 1. Add 'body' => $body
$content = str_replace(
    "'module' => \$m[1],",
    "'module' => \$m[1],\n                'body' => \$body,",
    $content
);

// 2. Modify write() to extract @ingress and @scheduled and add them to docblock
$search = "\$php = <<<PHP\n        <?php\n\n        declare(strict_types=1);\n\n        /**\n         * ⛔ GENERATED by `module:scaffold` from the documented header. DO NOT EDIT.\n         *\n         * A hand-edited manifest is a manifest that drifts, and every stale-record\n         * defect in this programme was a hand-maintained file. Change the header,\n         * re-run the scaffold.\n         *\n         * @module {\$h['module']}\n         * @intent {\$h['intent']}\n         */";

$replacement = <<<PHP
        \$extra_doc = '';
        if (isset(\$h['body'])) {
            preg_match_all('/@ingress\s+[a-z][a-z0-9_.]+\s+<[^>]+>/i', \$h['body'], \$mi);
            preg_match_all('/@scheduled\s+[a-z][a-z0-9_.]+\s+<[^>]+>\s+@owner\s+(?:X|C)-[A-Za-z0-9]+/i', \$h['body'], \$ms);
            
            \$extras = [];
            foreach (\$mi[0] as \$match) {
                \$extras[] = '         * ' . \$match;
            }
            foreach (\$ms[0] as \$match) {
                \$extras[] = '         * ' . \$match;
            }
            if (!empty(\$extras)) {
                \$extra_doc = "\\n" . implode("\\n", \$extras);
            }
        }

        \$php = <<<PHP
        <?php

        declare(strict_types=1);

        /**
         * ⛔ GENERATED by \`module:scaffold\` from the documented header. DO NOT EDIT.
         *
         * A hand-edited manifest is a manifest that drifts, and every stale-record
         * defect in this programme was a hand-maintained file. Change the header,
         * re-run the scaffold.
         *
         * @module {\$h['module']}
         * @intent {\$h['intent']}{\$extra_doc}
         */
PHP;

$content = str_replace($search, $replacement, $content);
file_put_contents($file, $content);
