<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 31 capability(ies) for X-221.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-221/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'G3-49' => '§44 · P-128 — audience building is ad management',

    // status: SUPERSEDED
    'G14-01' => 'ad-blindness rotation plan',

    // status: SUPERSEDED
    'G14-03' => 'addressable geo-fence plan',

    // status: SUPERSEDED
    'G14-04' => 'audience decay detection from reports',

    // status: SUPERSEDED
    'G14-05' => 'audience rotation plan',

    // status: SUPERSEDED
    'G14-08' => 'split-test PLAN (not execution)',

    // status: SUPERSEDED
    'G14-09' => 'budget detection from reports',

    // status: SUPERSEDED
    'G14-10' => 'budget-shift recommendation',

    // status: SUPERSEDED
    'G14-11' => 'click-farm signals from reports refuses',

    // status: SUPERSEDED
    'G14-12' => 'competitor-blocking advice',

    // status: SUPERSEDED
    'G14-14' => 'copy generation — advisory',

    // status: SUPERSEDED
    'G14-15' => 'copy vs creative analysis from imported reports',

    // status: SUPERSEDED
    'G14-16' => 'CRM audience lists exported for upload',

    // status: SUPERSEDED
    'G14-17' => 'cross-sell retargeting plan',

    // status: SUPERSEDED
    'G14-18' => 'CTR tracking from imported reports',

    // status: SUPERSEDED
    'G14-19' => 'dayparting analysis from reports',

    // status: SUPERSEDED
    'G14-21' => 'dynamic retargeting plan',

    // status: SUPERSEDED
    'G14-24' => 'localized ad variations',

    // status: SUPERSEDED
    'G14-27' => 'multi-tier generation',

    // status: SUPERSEDED
    'G14-28' => 'negative lookalike lists, exported as CSV',

    // status: SUPERSEDED
    'G14-30' => 'price-test plan refuses',

    // status: SUPERSEDED
    'G14-31' => 'revival-test plan',

    // status: SUPERSEDED
    'G14-32' => 'sequential retargeting plan',

    // status: SUPERSEDED
    'G14-33' => 'switch-and-save campaign plan refuses',

    // status: SUPERSEDED
    'G14-34' => 'visual pin-drop geo plan',

    // status: SUPERSEDED
    'G14-35' => 'wasted-spend findings, as advice refuses',

    // status: SUPERSEDED
    'G14-36' => 'weather overlay advice',

    // status: SUPERSEDED
    'G14-37' => 'weather-trigger advice',

    // status: SUPERSEDED
    'G14-38' => 'win-back lookalike lists exported',

    // status: SPECCED
    'G16-26' => '§44 · P-128 — retargeting a viewer is ad management.  The watch-depth SIGNAL survives (X-158 → P-068)',

    // status: SPECCED
    'G17-14' => '§44 · P-128 — location-history ad targeting is ad management',
];
