<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 10 capability(ies) for X-114.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-114/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'G5-06' => 'image tagging on the Asset',

    // status: SPECCED
    'G16-01' => 'stock for a DEMO page only;  P-131 — a job photo is never stock',

    // status: SPECCED
    'G16-04' => 'signed upload URL; the Asset row is X-121\'s · refuses: an upload without a signed URL',

    // status: SPECCED
    'G16-08' => 'generated, compressed, never a broken placeholder',

    // status: SPECCED
    'G16-09' => 'a design source feeding the asset library',

    // status: SPECCED
    'G16-13' => '= AI Stock Sourcing; one spec',

    // status: SPECCED
    'G16-20' => 'transcoding to each channel\'s limits refuses',

    // status: SPECCED
    'G16-29' => 'ad packs as content (P-128); the logo and palette come from the brand kit',

    // status: SPECCED
    'G16-31' => 'the recipient\'s address on every page',

    // status: SPECCED
    'G17-08' => 'one master → every size, WebP',
];
