<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 7 capability(ies) for X-205.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-205/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'G7-04' => 'refuses: AffiliateProgram; ref merged with utm — see §166.5',

    // status: SPECCED
    'G7-11' => 'refuses: AffiliateProgram; a chargeback reverses a paid commission; X-201 raises the event',

    // status: SPECCED
    'G7-23' => 'refuses: AffiliateProgram; self-clicking and stolen-card affiliates',

    // status: SPECCED
    'G7-41' => 'refuses: AffiliateProgram; referral tiers unlock by count',

    // status: SPECCED
    'G7-45' => 'refuses: AffiliateProgram; the partner\'s own login — clicks, pending earnings, swipe files',

    // status: SPECCED
    'G10-36' => 'W-9 threshold freezes a payout;  Law 122 — the switch and the threshold as data, never the advice',

    // status: SPECCED
    'G13-20' => 'the minted engine\'s core clock — a 90-day cookie and a lifetime balance',
];
