<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 5 capability(ies) for X-102.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-102/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'G2-57' => 'capture-first; the chat never dead-ends',

    // status: SPECCED
    'G8-36' => 'the widget\'s Shadow DOM; the page-reading half feeds X-119',

    // status: SPECCED
    'G13-15' => 'the pixel triggers; the chat answers grounded (X-119)',

    // status: SPECCED
    'G13-37' => 'the widget offers help instead of watching them fail',

    // status: SPECCED
    'G16-21' => 'carousels rendered in the chat',
];
