<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 3 capability(ies) for X-151.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-151/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'G3-44' => 'the proxy pool is X-151\'s;  P-145 sets a global concurrency and RPS ceiling — "never IP-banned" is not the goal; polite is',

    // status: SPECCED
    'G3-63' => 'a headless screenshot stored as an Asset (X-121)',

    // status: SPECCED
    'G17-13' => 'async, under the global per-target RPS ceiling (P-145)',
];
