<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 9 capability(ies) for X-162.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-162/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'G2-29' => 'named in the header',

    // status: SPECCED
    'G2-41' => 'named in the header',

    // status: SPECCED
    'G2-54' => 'named in the header; the sequence fires through X-186',

    // status: SPECCED
    'G2-55' => '= G2-54; one spec. The Zapier hop is native here (X-123)',

    // status: SPECCED
    'G2-65' => 'named in the header',

    // status: SPECCED
    'G2-71' => 'nearest tech — the third state (EN ROUTE) is what makes the answer true',

    // status: SPECCED
    'G2-73' => 'named in the header',

    // status: SPECCED
    'G2-77' => 'named in the header;  the multi-warehouse framing is out of scope — "a van and a storage unit, not a warehouse" (X-167)',

    // status: SPECCED
    'G4-11' => 'NAME COLLISION — X-195\'s header claims the term for manifests; this row is task dependencies',
];
