<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 5 capability(ies) for X-184.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-184/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'G5-49' => 'approve a cadence, never a topic list; ad PACKS as content are not fenced (P-128)',

    // status: SPECCED
    'G9-16' => 'creative fatigue → refresh the content pack; ad PACKS as content are not fenced (P-128)',

    // status: SPECCED
    'G12-13' => 'a RECOMMEND, never an auto-post',

    // status: SPECCED
    'G12-36' => 'a trend proposes a topic; the cadence is what the tenant approved',

    // status: SPECCED
    'G16-16' => 'approve a cadence, never a topic list',
];
