<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 16 capability(ies) for X-105.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-105/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'G1-25' => 'P-068 — the signal raises; X-204 decides, asserted by absence of a permit write in this module',

    // status: SPECCED
    'G1-26' => 'every opener clause traces to a Fact, asserted; research fires only on distress (P-146), asserted by running it on a healthy prospect and observing no research refuses',

    // status: SPECCED
    'G3-07' => 'a reply stops the ladder (P-075); the nurture branch is X-186\'s',

    // status: SPECCED
    'G3-09' => 'named in the header',

    // status: SPECCED
    'G3-17' => 'the battle card lands in the reply refuses',

    // status: SPECCED
    'G3-21' => 'rung ④, the voicemail drop',

    // status: SPECCED
    'G3-30' => 'named in the header (P-075)',

    // status: SPECCED
    'G3-38' => 'named in the header',

    // status: SPECCED
    'G3-43' => 'the battle card attaches to the reply',

    // status: SPECCED
    'G5-20' => 'named in the header',

    // status: SPECCED
    'G5-27' => '= G5-20; one spec',

    // status: SPECCED
    'G11-35' => 'the cold opener from X-135\'s research (P-146 — distress only) · refuses: an opener without distress (P-146)',

    // status: SPECCED
    'G17-02' => 'named in the header',

    // status: SPECCED
    'G19-19' => 'the battle card drafted into a reply the human sends refuses',

    // status: SPECCED
    'G20-10' => 'named in the header — under 3.5★ is a distress signal (P-146) · refuses: targeting over 3.5★ — under 3.5★ is the distress signal (P-146)',

    // status: SPECCED
    'G15-15' => '',
];
