<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 9 capability(ies) for X-210.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-210/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'G18-05' => 'P-001 · T468 — two packages, and everything we ship, as we ship it, at the price you joined at. There is no locked tier to show a padlock for',

    // status:
    'N-027' => 'no cap → cannot save · margin guard NAMES every below-cost service · no stacking by default · the AI honours and never invents · issuer_scope never crosses · incrementality holdout mandatory',

    // status:
    'N-032' => 'no cap → cannot save · margin guard NAMES every below-cost service · no stacking by default · the AI honours and never invents · issuer_scope never crosses · incrementality holdout mandatory',

    // status: SPECCED
    'G1-66' => '§226.2 — a promotion with no cap CANNOT BE SAVED · transcribed from the plan 2026-08-27 · ⛔ register description STRIPPED (P-206) — it lives in the register, not in the file the brief reads · ⑤ a promotion with NO CAP cannot be saved — asserted',

    // status: SPECCED
    'G1-67' => '§226.2 — the margin guard NAMES every service put below cost · transcribed from the plan 2026-08-27 · ⛔ register description STRIPPED (P-206) — it lives in the register, not in the file the brief reads · ⑤ the margin guard NAMES every service put below cost — asserted',

    // status: SPECCED
    'G1-69' => '§226.2 — R34: the offer and CANCEL on one screen, cancel always one tap · transcribed from the plan 2026-08-27 · ⛔ register description STRIPPED (P-206) — it lives in the register, not in the file the brief reads · ⑤ R34: no interstitial exists between the cancel tap and the cancellation — asserted BY ABSENCE',

    // status: SPECCED
    'G6-38' => '§226.2 — with R34: no interstitial exists, by absence · transcribed from the plan 2026-08-27 · ⛔ register description STRIPPED (P-206) — it lives in the register, not in the file the brief reads · ⑤ R34: cancel stays one tap; the offer renders beside it, never in front of it refuses',

    // status: SPECCED
    'G7-47' => '§226.2 — a cohort rate is a ROW; an existing tenant\'s rate never changes without a NOTIFIED action · transcribed from the plan 2026-08-27 · ⛔ register description STRIPPED (P-206) — it lives in the register, not in the file the brief reads · ⑤ a cohort rate is a ROW; an existing rate never changes without a NOTIFIED action — asserted',

    // status: SPECCED
    'G15-21' => 'reclaimed 2026-08-27 · ⛔ register description STRIPPED (P-206) — it lives in the register, not in the file the brief reads · ⑤ R34 overrides: cancel stays ONE TAP; the save-offer renders beside it · refuses: anything but one tap to cancel refuses',
];
