<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 8 capability(ies) for X-210.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-210/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'G18-05' => 'P-001 · T468 — two packages, and everything we ship, as we ship it, at the price you joined at. There is no locked tier to show a padlock for',

    // status: 
    'N-027' => '',

    // status: SPECCED
    'G1-66' => '',

    // status: SPECCED
    'G1-67' => '',

    // status: SPECCED
    'G1-69' => '',

    // status: SPECCED
    'G6-38' => ' refuses',

    // status: SPECCED
    'G7-47' => '',

    // status: SPECCED
    'G15-21' => ' refuses',
];
