<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 8 capability(ies) for X-118.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-118/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'G1-24' => 'asserted: the AI answers the phone and books jobs BEFORE any of gateway, KYC or domain is connected (§201A · §203) — every one of those is a pending TASK, never a gate ·  the wizard INFERS and confirms once; doctor asserts no onboarding step is a hard stop',

    // status: SPECCED
    'G1-38' => 'asserted: the AI answers the phone and books jobs BEFORE any of gateway, KYC or domain is connected (§201A · §203) — every one of those is a pending TASK, never a gate ·  the wizard INFERS and confirms once; doctor asserts no onboarding step is a hard stop',

    // status: SPECCED
    'G3-01' => 'X-118 needs a name and a number, not a URL — this is the same inference run with a weaker input',

    // status: SPECCED
    'G4-01' => 'TTFM and the no-login nudge',

    // status: SPECCED
    'G4-38' => 'SAMPLE → real on conversion;  the $179.99 figure is dead (money-number law) refuses',

    // status: SPECCED
    'G4-44' => 'frictionless signup, magic link, no password refuses',

    // status: SPECCED
    'G4-45' => 'the hub is a generated index over every module\'s .connect action (X-122) — not a module',

    // status: SPECCED
    'G5-05' => 'the whole module is an inference run',
];
