<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 20 capability(ies) for X-167.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-167/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'G1-58' => 'it PROPOSES a purchase with the ranked options; doctor asserts no purchase API call exists in this module',

    // status: SPECCED
    'G2-24' => 'SKU scan — the FSM bucket C4 must add (G1\'s structural finding)',

    // status: SPECCED
    'G6-08' => 'barcode generation — the FSM bucket C4 must add',

    // status: SPECCED
    'G6-14' => 'fractional units — "a van and a storage unit, not a warehouse" bounds it',

    // status: SPECCED
    'G6-18' => 'multi-warehouse shipping — same scope note as G2-77',

    // status: SPECCED
    'G6-22' => 'Shopify/WooCommerce stock sync',

    // status: SPECCED
    'G6-24' => 'retail stock across locations',

    // status: SPECCED
    'G17-15' => 'in-browser barcode scan',

    // status: SPECCED
    'G19-02' => 'parcel rates;  a van and a storage unit, not a warehouse bounds it',

    // status: SPECCED
    'G1-64' => '',

    // status: SPECCED
    'G1-76' => '',

    // status: SPECCED
    'G1-79' => '',

    // status: SPECCED
    'G6-39' => '',

    // status: SPECCED
    'G6-40' => '',

    // status: SPECCED
    'G6-43' => '',

    // status: SPECCED
    'G6-46' => '',

    // status: SPECCED
    'G6-47' => '',

    // status: SPECCED
    'G6-48' => '',

    // status: SPECCED
    'G6-49' => '',

    // status: SPECCED
    'G6-51' => '',
];
