<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by \`module:scaffold\` from the documented header. DO NOT EDIT.
 *
 * A hand-edited manifest is a manifest that drifts, and every stale-record
 * defect in this programme was a hand-maintained file. Change the header,
 * re-run the scaffold.
 *
 * @module X-167
 *
 * @intent INFORM under §227.2
 *
 * @ingress order.paid <vendor>
 * @ingress order.cancelled <vendor>
 */
return [
    'module' => 'X-167',
    'intent' => 'INFORM under §227.2',

    // ⛔⛔⛔ R235 — `ships` EQUALS `ceiling`. THE AUTOPILOT IS ON.
    //
    // This comment used to teach §227.2's intent default: "GROW ships
    // L1, PROPOSES ONLY, ALWAYS". The owner struck it — "ALL AI ON, by
    // my law. The client can turn it off if they want."
    //
    // ⭐ There is nothing to earn. @intent still DESCRIBES the action;
    //   it no longer gates when the action may run.
    'ships' => 'L3',
    'ceiling' => 'L3',

    'provides' => [
        'stock.adjust',
        'reorder.propose',
        'po.generate',
    ],
    'emits' => [
        'inventory.consumed',
        'reorder.triggered',
        'stock.low',
        'po.sent',
    ],
    'consumes' => [
        'job.completed',
        'barcode.scanned',
        'order.paid',
        'order.cancelled',
    ],

    // ⛔ P-163 — @owns_table may not name one of X-121's canonical nouns.
    'owns_table' => [
        'stock_items',
        'stock_locations',
        'purchase_orders',
        'suppliers',
    ],
    'reads_table' => [],

    'renders' => [
        'stock_by_van',
        'reorders',
    ],

    // P-209 — silence fails OPEN. `none` is a decision; absence is not.
    'agent_reachable' => [
        'none',
        'none',
        'none',
    ],
];
