<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 19 capability(ies) for X-01.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-01/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'G1-45' => 'the value is read through an action at render, never cached locally, asserted',

    // status: SPECCED
    'G2-16' => '"Rep A is typing" presence on the shared thread',

    // status: SPECCED
    'G2-18' => 'named in the header; one Person (P-163)',

    // status: SPECCED
    'G2-23' => 'named in the header',

    // status: SPECCED
    'G2-25' => 'D1: MASTER = Honest Counter for the tenant app; God-Mode/glassmorphism is console-only',

    // status: SPECCED
    'G2-32' => 'lead_scores; opens and clicks arrive from C-Mail refuses',

    // status: SPECCED
    'G2-36' => 'named in the header; the UTM itself is X-138\'s',

    // status: SPECCED
    'G2-38' => 'the grade is a lead_score; the data is X-134\'s and carries confidence (P-147)',

    // status: SPECCED
    'G2-42' => 'named in the header',

    // status: SPECCED
    'G2-61' => 'split: the score is a lead_score;  the lookalike-seed half is FENCED (§44 · P-128)',

    // status: SPECCED
    'G2-76' => 'the unified inbox is the header\'s first line',

    // status: SPECCED
    'G5-13' => 'the thread\'s three-bullet head',

    // status: SPECCED
    'G9-10' => 'named in the header (moved there from X-121)',

    // status: SPECCED
    'G11-22' => 'one polymorphic Conversation (X-121\'s) across every channel',

    // status: SPECCED
    'G11-23' => '= the row above; one spec',

    // status: SPECCED
    'G11-40' => 'the header\'s first line',

    // status: SPECCED
    'G11-41' => 'sort order on the thread list; the LTV is C-Billing\'s',

    // status: SPECCED
    'G19-08' => 'ghost-risk is named in the header — flagged before a send is wasted',

    // status: SPECCED
    'G19-15' => 'the thread updates without a refresh',
];
