<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 3 capability(ies) for X-127.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-127/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'N-127-01' => '⛔⛔ a published claim is RE-COMPUTED from the live query and must MATCH TO THE DIGIT — a drifted claim is PULLED AUTOMATICALLY, not flagged (§5 Law 3: no invented statistics, ever)',

    // status: SPECCED
    'N-127-02' => '§5 Law 2 — a module that fails for tenant #0 does not ship',

    // status: SPECCED
    'N-127-03' => '⛔ a GOAIEZ-scoped read returns ZERO rows belonging to any other tenant (R232 N-232-04) — tenant-zero does not relax the no-harvest fence',
];
