<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by \`module:scaffold\` from the documented header. DO NOT EDIT.
 *
 * A hand-edited manifest is a manifest that drifts, and every stale-record
 * defect in this programme was a hand-maintained file. Change the header,
 * re-run the scaffold.
 *
 * @module X-127
 *
 * @intent RECOVER
 */
return [
    'module' => 'X-127',
    'intent' => 'RECOVER',

    // ⛔⛔⛔ R235 — `ships` EQUALS `ceiling`. THE AUTOPILOT IS ON.
    //
    // This comment used to teach §227.2's intent default: "GROW ships
    // L1, PROPOSES ONLY, ALWAYS". The owner struck it — "ALL AI ON, by
    // my law. The client can turn it off if they want."
    //
    // ⭐ There is nothing to earn. @intent still DESCRIBES the action;
    //   it no longer gates when the action may run.
    'ships' => 'L3',
    'ceiling' => 'L3',

    'provides' => [
        'tenantzero.config',
        'tenantzero.metric',
        'tenantzero.proof',
    ],
    'emits' => [
        'none',
        'tenantzero.metric_published',
        'tenantzero.claim_verified',
    ],
    'consumes' => [
        'subscription.renewed',
        'job.completed',
        'review.received',
    ],

    // ⛔ P-163 — @owns_table may not name one of X-121's canonical nouns.
    'owns_table' => [
        'tenant_zero_config',
        'published_metrics',
    ],
    'reads_table' => [],

    'renders' => [
        'MetricProofPanel',
    ],

    // P-209 — silence fails OPEN. `none` is a decision; absence is not.
    'agent_reachable' => [
        'none',
        'none',
        'none',
    ],
];
