<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 7 capability(ies) for X-209.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-209/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status:
    'N-021' => 'refuses: employee → their own day; everything else in this platform acts tenant → customer',

    // status:
    'N-022' => 'refuses: its output NEVER reaches a customer; grep finds no send path to a non-staff Person',

    // status:
    'N-023' => 'refuses: per-EMPLOYEE autonomy; a new hire starts at L1 on everything (§227)',

    // status:
    'N-024' => 'whatever it does appears in the tenant\'s own log — never a hidden assistant',

    // status:
    'N-025' => 'refuses: it may not see another employee\'s secure fields; (P-198 — role AND job scoped)',

    // status:
    'N-026' => 'refuses: it refuses to answer about pay; P-204: the platform does not pay people, so its assistant does not discuss what they are owed',

    // status: SPECCED
    'N-209-01' => 'the employee\'s agent reaches only what THAT EMPLOYEE may reach — asserted per employee, not per tenant',
];
