<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 15 capability(ies) for X-183.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-183/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'G2-11' => 'R36\'s case-study machine — double consent, never automatic publication',

    // status: SPECCED
    'G5-11' => 'a negative comment on a draft; the escalation is the ApprovalDesk question',

    // status: SPECCED
    'G5-35' => 'R36 — drafts from REAL data only, double consent',

    // status: SPECCED
    'G6-04' => 'the case-study render; R36\'s double consent stands',

    // status: SPECCED
    'G7-24' => 'the pre-publish gate applied to a human\'s draft',

    // status: SPECCED
    'G8-39' => 'the AI writes gated by grounding; structure from the top-ranking analysis',

    // status: SPECCED
    'G9-17' => 'the summary is content, gated by the pre-publish gate',

    // status: SPECCED
    'G9-22' => 'hard numbers pulled from the client\'s own words (R36 — real data only)',

    // status: SPECCED
    'G12-02' => 'gated by grounding; the pre-publish gate is X-183\'s · refuses: publishing without grounding',

    // status: SPECCED
    'G12-05' => 'to the builder or the plugin refuses',

    // status: SPECCED
    'G12-29' => 'named in the header — cannibalisation · SAMPLE prices never rendered · nothing contradicts the pricebook',

    // status: SPECCED
    'G13-29' => 'the gate cites or rejects · refuses: accepting without citation',

    // status: SPECCED
    'G16-03' => 'long-form structure through the gate',

    // status: SPECCED
    'G16-28' => 'transcript → post, through the gate',

    // status: SPECCED
    'G20-15' => 'a real review inside the case study (R36 — real data only)',
];
