<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 6 capability(ies) for X-156.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-156/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'G2-05' => 'Salesforce/HubSpot/GHL as ingest sources — nothing sits in a staging table',

    // status: SPECCED
    'G2-31' => 'every contact write carries an attestation_id or is refused (P-069)',

    // status: SPECCED
    'G2-46' => 'named in the header; the HMAC-verified door',

    // status: SPECCED
    'G3-23' => 'a scan is a source; the QR rides the short-linker (P-072)',

    // status: SPECCED
    'G5-34' => 'Housecall Pro / ServiceTitan / Jobber as sources; X-129 migrates them in',

    // status: SPECCED
    'G17-05' => 'Drive and Notion as ingest sources',
];
