<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 3 capability(ies) for X-218.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-218/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'N-218-01' => '⛔⛔⛔ a payout NEVER fires without a VERIFIED deliverable — a live URL returning 200, captured and HASHED, asserted present before C-Billing is called. A deal marked delivered with NO ARTIFACT is REFUSED refuses',

    // status: SPECCED
    'N-218-02' => 'discovery returns only profiles matching audience fit and locality; an unscoped pull is refused',

    // status: SPECCED
    'N-218-03' => '⭐ the same module serves tenant and GOAIEZ scope (R232) — a TENANT-scoped read returns ZERO GOAIEZ deals and the reverse',
];
