<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 5 capability(ies) for X-185.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-185/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'G5-16' => 'a gap in the calendar is a signal, not a permit (P-068) — the send runs Lane 2 through ConsentService',

    // status: SPECCED
    'G12-20' => 'it may test a label, never a price (§134.6)',

    // status: SPECCED
    'G12-30' => 'fleet evidence, never four data points at one tenant',

    // status: SPECCED
    'G16-12' => 'named in the header',

    // status: SPECCED
    'G17-01' => 'opening lines; fleet evidence before promotion',
];
