<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by \`module:scaffold\` from the documented header. DO NOT EDIT.
 *
 * A hand-edited manifest is a manifest that drifts, and every stale-record
 * defect in this programme was a hand-maintained file. Change the header,
 * re-run the scaffold.
 *
 * @module X-185
 *
 * @intent GROW under §227.2
 *
 * @ingress entity.state_changed <system>
 * @ingress entity.state_changed <system>
 */
return [
    'module' => 'X-185',
    'intent' => 'GROW under §227.2',

    // ⛔⛔⛔ R235 — `ships` EQUALS `ceiling`. THE AUTOPILOT IS ON.
    //
    // This comment used to teach §227.2's intent default: "GROW ships
    // L1, PROPOSES ONLY, ALWAYS". The owner struck it — "ALL AI ON, by
    // my law. The client can turn it off if they want."
    //
    // ⭐ There is nothing to earn. @intent still DESCRIBES the action;
    //   it no longer gates when the action may run.
    'ships' => 'L2',
    'ceiling' => 'L2',

    'provides' => [
        'campaign.create',
        'campaign.run',
        'sequence.stop',
        'pack.seed',
    ],
    'emits' => [
        'variant.promoted',
        'variant.retired',
        'element.frozen',
    ],
    'consumes' => [
        'entity.state_changed',
        'signal.detected',
        'form.abandoned',
        'message.received',
        'tenant.created',
    ],

    // ⛔ P-163 — @owns_table may not name one of X-121's canonical nouns.
    'owns_table' => [
        'sequences',
        'sequence_steps',
        'content_packs',
    ],
    'reads_table' => [
        'campaigns',
    ],

    'renders' => [
        'digest_line',
        'experiment_board',
    ],

    // P-209 — silence fails OPEN. `none` is a decision; absence is not.
    'agent_reachable' => [
        'none',
        'none',
        'none',
    ],
];
