<?php

return [
    'entries' => [
        [
            'surface' => 'tenant',
            'label' => 'Today',
            'blurb' => 'Home — what needs you',
            'modules' => [
                'X-124',
                'X-199',
                'X-110',
                'X-118',
            ],
        ],
        [
            'surface' => 'tenant',
            'label' => 'Inbox',
            'blurb' => 'one thread per person, every channel; the AI front desk works inside it (staff desk, omni chat)',
            'modules' => [
                'X-01',
                'C-Sms',
                'C-Mail',
                'C-Whatsapp',
                'X-102',
                'C-Agent',
                'X-124',
                'X-194',
            ],
        ],
        [
            'surface' => 'tenant',
            'label' => 'Calls & Voice',
            'blurb' => 'the voice agent, missed-call text-back, recordings, the pool number state',
            'modules' => [
                'X-66',
                'C-Telephony',
                'X-188',
                'X-153',
                'X-137',
            ],
        ],
        [
            'surface' => 'tenant',
            'label' => 'Customers',
            'blurb' => 'contacts, pipeline, routing, calendar & appointments, agreements & e-sign, churn',
            'modules' => [
                'X-01',
                'X-10',
                'X-108',
                'X-07',
                'X-08',
                'X-132',
                'X-131',
                'X-164',
            ],
        ],
        [
            'surface' => 'tenant',
            'label' => 'Jobs & Field',
            'blurb' => 'dispatch board, jobs, technician app, timesheets, job costing, inventory, customer portal',
            'modules' => [
                'X-162',
                'X-171',
                'X-168',
                'X-166',
                'X-167',
                'X-172',
                'X-175',
            ],
        ],
        [
            'surface' => 'tenant',
            'label' => 'Pricebook',
            'blurb' => 'the one screen four modules read; price confirmation; memberships',
            'modules' => [
                'X-163',
                'X-165',
                'X-82',
            ],
        ],
        [
            'surface' => 'tenant',
            'label' => 'Money',
            'blurb' => 'invoices, payments & cart/checkout, card vault, merchant account application, disputes, receivables, credits, taxes',
            'modules' => [
                'X-199',
                'X-198',
                'X-120',
                'X-117',
                'X-201',
                'X-211',
                'C-Billing',
                'X-173',
            ],
        ],
        [
            'surface' => 'tenant',
            'label' => 'Reviews',
            'blurb' => 'requests, triage, QA report, tickets, loss alerts, GBP guardian',
            'modules' => [
                'C-Reviews',
                'X-181',
                'X-177',
            ],
        ],
        [
            'surface' => 'tenant',
            'label' => 'Marketing',
            'blurb' => 'broadcasts & sequences, social & content week, video, promotions, referrals, ads advisor',
            'modules' => [
                'X-186',
                'X-125',
                'X-207',
                'X-180',
                'X-182',
                'X-183',
                'X-184',
                'X-185',
                'X-189',
                'X-210',
                'X-190',
            ],
        ],
        [
            'surface' => 'tenant',
            'label' => 'Website',
            'blurb' => 'builder, pages, templates, AI designer, forms, hosting/SSL, migration, WordPress plugin, storefront',
            'modules' => [
                'X-103',
                'X-116',
                'X-178',
                'X-179',
                'X-155',
                'X-157',
                'X-129',
                'X-212',
                'X-104',
                'X-117',
            ],
        ],
        [
            'surface' => 'tenant',
            'label' => 'Visibility',
            'blurb' => 'SEO & AEO, GBP, citations, backlinks, AI visibility',
            'modules' => [
                'X-140',
                'X-176',
                'X-191',
                'X-192',
                'X-130',
            ],
        ],
        [
            'surface' => 'tenant',
            'label' => 'Prospecting',
            'blurb' => 'scraping, enrichment, research, signals, the Chrome extension, outreach ladder',
            'modules' => [
                'X-151',
                'X-150',
                'X-156',
                'X-134',
                'X-135',
                'X-136',
                'X-16',
                'X-196',
                'X-109',
                'X-105',
            ],
        ],
        [
            'surface' => 'tenant',
            'label' => 'Visitors & Attribution',
            'blurb' => 'live visitors, COOLING, abandoned forms, install & verify, attribution row, replay, reports',
            'modules' => [
                'X-110',
                'X-138',
                'X-139',
            ],
        ],
        [
            'surface' => 'tenant',
            'label' => 'Automations & Assistant',
            'blurb' => 'the canvas, runs, safe mode; the omni assistant configures anything; integrations, MCP, Zapier',
            'modules' => [
                'X-125',
                'X-124',
                'X-194',
                'X-142',
                'X-122',
            ],
        ],
        [
            'surface' => 'tenant',
            'label' => 'Settings',
            'blurb' => 'agent, numbers, hours & notification rules, consent & compliance, staff & roles, billing plan, credential vault, legal desk, white-label',
            'modules' => [
                'X-193',
                'X-204',
                'X-113',
                'X-206',
                'C-Billing',
                'X-127',
                'C-Ai',
                'X-119',
                'X-121',
                'X-123',
                'X-126',
                'X-128',
                'X-148',
                'X-149',
                'X-154',
                'X-160',
                'X-161',
                'X-219',
                'X-220',
            ],
        ],
        [
            'surface' => 'other',
            'label' => 'Operator console',
            'blurb' => 'alerts (action, never a fact), approvals, resiliency, fixer, vision QA, tenant zero, support tickets, data requests, reconciliation & dispute queues',
            'modules' => [
                'X-111',
                'X-202',
                'X-203',
                'X-209',
                'X-127',
                'X-198',
                'X-201',
            ],
        ],
        [
            'surface' => 'other',
            'label' => 'Agency console',
            'blurb' => 'clients, agency billing (three modes), staff roles, marketplace, white-label branding, affiliate program',
            'modules' => [
                'X-112',
                'X-113',
                'X-195',
                'X-205',
                'X-217',
                'X-218',
                'X-170',
            ],
        ],
        [
            'surface' => 'other',
            'label' => 'Technician mobile',
            'blurb' => 'offline-first job app, field assistant',
            'modules' => [
                'X-171',
                'X-175',
            ],
        ],
    ],
    'deferred' => [],
];
