<?php

return [
    'tenant' => [
        'Settings' => [
            ['label' => 'Thread', 'route' => 'c-agent.thread', 'module' => 'C-Agent'],
            ['label' => 'Groundcheck Screen', 'route' => 'c-agent.groundcheck-screen', 'module' => 'C-Agent'],
            ['label' => 'Teaching Box', 'route' => 'c-agent.teaching-box', 'module' => 'C-Agent'],
            ['label' => 'Refusalcode Distribution Per', 'route' => 'c-agent.refusalcode-distribution-per', 'module' => 'C-Agent'],
            ['label' => 'Model Board', 'route' => 'c-ai.model-board', 'module' => 'C-Ai'],
            ['label' => 'Agency Console', 'route' => 'x-112.agency-console', 'module' => 'X-112'],
            ['label' => 'Staff', 'route' => 'x-112.staff', 'module' => 'X-112'],
            ['label' => 'Roles', 'route' => 'x-112.roles', 'module' => 'X-112'],
            ['label' => 'Impersonation Log', 'route' => 'x-112.impersonation-log', 'module' => 'X-112'],
            ['label' => 'Staff', 'route' => 'x-113.staff', 'module' => 'X-113'],
            ['label' => 'Roles', 'route' => 'x-113.roles', 'module' => 'X-113'],
            ['label' => 'Permission Matrix', 'route' => 'x-113.permission-matrix', 'module' => 'X-113'],
            ['label' => 'Document Vault', 'route' => 'x-113.document-vault', 'module' => 'X-113'],
            ['label' => 'Brand Kit', 'route' => 'x-114.brand-kit', 'module' => 'X-114'],
            ['label' => 'Media Library', 'route' => 'x-114.media-library', 'module' => 'X-114'],
            ['label' => 'Cart Block', 'route' => 'x-117.cart-block', 'module' => 'X-117'],
            ['label' => 'Checkout Block', 'route' => 'x-117.checkout-block', 'module' => 'X-117'],
            ['label' => 'Reviewwhatifound Screen', 'route' => 'x-119.reviewwhatifound-screen', 'module' => 'X-119'],
            ['label' => 'Price Confirmation Screen', 'route' => 'x-119.price-confirmation-screen', 'module' => 'X-119'],
            ['label' => 'Teaching Box', 'route' => 'x-119.teaching-box', 'module' => 'X-119'],
            ['label' => 'Fact Freshness Per', 'route' => 'x-119.fact-freshness-per', 'module' => 'X-119'],
            ['label' => 'Demand Tile', 'route' => 'x-130.demand-tile', 'module' => 'X-130'],
            ['label' => 'Public Index Pages', 'route' => 'x-130.public-index-pages', 'module' => 'X-130'],
            ['label' => 'Coverage By Trade', 'route' => 'x-130.coverage-by-trade', 'module' => 'X-130'],
            ['label' => 'Cooling', 'route' => 'x-136.cooling', 'module' => 'X-136'],
            ['label' => 'Signal Volume Precision', 'route' => 'x-136.signal-volume-precision', 'module' => 'X-136'],
            ['label' => 'Proposed Pages', 'route' => 'x-140.proposed-pages', 'module' => 'X-140'],
            ['label' => 'Connect Your Ai', 'route' => 'x-142.connect-your-ai', 'module' => 'X-142'],
            ['label' => 'Webhooks', 'route' => 'x-142.webhooks', 'module' => 'X-142'],
            ['label' => 'Mcp Token Registry', 'route' => 'x-142.mcp-token-registry', 'module' => 'X-142'],
            ['label' => 'Visibility Tile', 'route' => 'x-144.visibility-tile', 'module' => 'X-144'],
            ['label' => 'Question List', 'route' => 'x-144.question-list', 'module' => 'X-144'],
            ['label' => 'Tenant Zeros Own', 'route' => 'x-144.tenant-zeros-own', 'module' => 'X-144'],
            ['label' => 'Proposals Appear Today', 'route' => 'x-145.proposals-appear-today', 'module' => 'X-145'],
            ['label' => 'Readback Screen', 'route' => 'x-154.readback-screen', 'module' => 'X-154'],
            ['label' => 'Connect Source', 'route' => 'x-156.connect-source', 'module' => 'X-156'],
            ['label' => 'Rejectedrows List', 'route' => 'x-156.rejectedrows-list', 'module' => 'X-156'],
            ['label' => 'Ingest Volume By', 'route' => 'x-156.ingest-volume-by', 'module' => 'X-156'],
            ['label' => 'Prospectfacing Video Demo', 'route' => 'x-158.prospectfacing-video-demo', 'module' => 'X-158'],
            ['label' => 'Content Plans Video', 'route' => 'x-158.content-plans-video', 'module' => 'X-158'],
            ['label' => 'Render Queue', 'route' => 'x-158.render-queue', 'module' => 'X-158'],
            ['label' => 'Customerprospectfacing Audit Page', 'route' => 'x-159.customerprospectfacing-audit-page', 'module' => 'X-159'],
            ['label' => 'Score', 'route' => 'x-159.score', 'module' => 'X-159'],
            ['label' => 'Audit Queue', 'route' => 'x-159.audit-queue', 'module' => 'X-159'],
            ['label' => 'Geogrid Map', 'route' => 'x-16.geogrid-map', 'module' => 'X-16'],
            ['label' => 'Servicearea Polygon', 'route' => 'x-16.servicearea-polygon', 'module' => 'X-16'],
            ['label' => 'Harvest Coverage By', 'route' => 'x-16.harvest-coverage-by', 'module' => 'X-16'],
            ['label' => 'Upload Drop', 'route' => 'x-160.upload-drop', 'module' => 'X-160'],
            ['label' => 'Review Screen', 'route' => 'x-160.review-screen', 'module' => 'X-160'],
            ['label' => 'Extraction Error Rate', 'route' => 'x-160.extraction-error-rate', 'module' => 'X-160'],
            ['label' => 'Estimates List', 'route' => 'x-164.estimates-list', 'module' => 'X-164'],
            ['label' => 'Timesheets', 'route' => 'x-168.timesheets', 'module' => 'X-168'],
            ['label' => 'Approvals', 'route' => 'x-168.approvals', 'module' => 'X-168'],
            ['label' => 'Own Hours', 'route' => 'x-168.own-hours', 'module' => 'X-168'],
            ['label' => 'Seo Tab Website', 'route' => 'x-176.seo-tab-website', 'module' => 'X-176'],
            ['label' => 'Gbp Card', 'route' => 'x-177.gbp-card', 'module' => 'X-177'],
            ['label' => 'Suspensionrisk Events Fleetwide', 'route' => 'x-177.suspensionrisk-events-fleetwide', 'module' => 'X-177'],
            ['label' => 'Marketplace', 'route' => 'x-195.marketplace', 'module' => 'X-195'],
            ['label' => 'Manifest Review Queue', 'route' => 'x-195.manifest-review-queue', 'module' => 'X-195'],
            ['label' => 'Connect Card', 'route' => 'x-198.connect-card', 'module' => 'X-198'],
            ['label' => 'Same Account', 'route' => 'x-198.same-account', 'module' => 'X-198'],
            ['label' => 'Reconciliation Discrepancies', 'route' => 'x-198.reconciliation-discrepancies', 'module' => 'X-198'],
            ['label' => 'Money Paid Today', 'route' => 'x-199.money-paid-today', 'module' => 'X-199'],
            ['label' => 'Unpaid', 'route' => 'x-199.unpaid', 'module' => 'X-199'],
            ['label' => 'Declines', 'route' => 'x-199.declines', 'module' => 'X-199'],
            ['label' => 'Invoices', 'route' => 'x-199.invoices', 'module' => 'X-199'],
            ['label' => 'Credits', 'route' => 'x-199.credits', 'module' => 'X-199'],
            ['label' => 'Queue', 'route' => 'x-202.queue', 'module' => 'X-202'],
            ['label' => 'Item', 'route' => 'x-202.item', 'module' => 'X-202'],
            ['label' => 'Audit Export', 'route' => 'x-202.audit-export', 'module' => 'X-202'],
            ['label' => 'Mobile', 'route' => 'x-202.mobile', 'module' => 'X-202'],
            ['label' => 'Slack', 'route' => 'x-202.slack', 'module' => 'X-202'],
            ['label' => 'Dr Dashboard', 'route' => 'x-203.dr-dashboard', 'module' => 'X-203'],
            ['label' => 'Restorationtest Log', 'route' => 'x-203.restorationtest-log', 'module' => 'X-203'],
            ['label' => 'Runbook Runner', 'route' => 'x-203.runbook-runner', 'module' => 'X-203'],
            ['label' => 'Portal', 'route' => 'x-205.portal', 'module' => 'X-205'],
            ['label' => 'Earnings', 'route' => 'x-205.earnings', 'module' => 'X-205'],
            ['label' => 'Payout Run', 'route' => 'x-205.payout-run', 'module' => 'X-205'],
            ['label' => 'Connections', 'route' => 'x-206.connections', 'module' => 'X-206'],
            ['label' => 'Reveal', 'route' => 'x-206.reveal', 'module' => 'X-206'],
            ['label' => 'Reveal Log', 'route' => 'x-206.reveal-log', 'module' => 'X-206'],
            ['label' => 'One Confirmonce Toggle', 'route' => 'x-207.one-confirmonce-toggle', 'module' => 'X-207'],
            ['label' => 'Promptcopy Editor', 'route' => 'x-207.promptcopy-editor', 'module' => 'X-207'],
            ['label' => 'Retirement Reasons', 'route' => 'x-207.retirement-reasons', 'module' => 'X-207'],
            ['label' => 'Perplatform Delivery Health', 'route' => 'x-207.perplatform-delivery-health', 'module' => 'X-207'],
            ['label' => 'Piece Preview', 'route' => 'x-208.piece-preview', 'module' => 'X-208'],
            ['label' => 'Cost', 'route' => 'x-208.cost', 'module' => 'X-208'],
            ['label' => 'Send Record', 'route' => 'x-208.send-record', 'module' => 'X-208'],
            ['label' => 'Private Inbox', 'route' => 'x-209.private-inbox', 'module' => 'X-209'],
            ['label' => 'Onetap Approval Card', 'route' => 'x-209.onetap-approval-card', 'module' => 'X-209'],
            ['label' => 'Ladders Own State', 'route' => 'x-209.ladders-own-state', 'module' => 'X-209'],
            ['label' => 'Never Setting', 'route' => 'x-209.never-setting', 'module' => 'X-209'],
            ['label' => 'Promotion Builder', 'route' => 'x-210.promotion-builder', 'module' => 'X-210'],
            ['label' => 'Active Promotions', 'route' => 'x-210.active-promotions', 'module' => 'X-210'],
            ['label' => 'Redemptions', 'route' => 'x-210.redemptions', 'module' => 'X-210'],
            ['label' => 'Earnedvsgiven Panel', 'route' => 'x-210.earnedvsgiven-panel', 'module' => 'X-210'],
            ['label' => 'Targeting Preview', 'route' => 'x-210.targeting-preview', 'module' => 'X-210'],
            ['label' => 'Ageing By Reason', 'route' => 'x-211.ageing-by-reason', 'module' => 'X-211'],
            ['label' => 'Invoice Thread Beside', 'route' => 'x-211.invoice-thread-beside', 'module' => 'X-211'],
            ['label' => 'Paymentplan Builder', 'route' => 'x-211.paymentplan-builder', 'module' => 'X-211'],
            ['label' => 'Collections Package Preview', 'route' => 'x-211.collections-package-preview', 'module' => 'X-211'],
            ['label' => 'Pick Source', 'route' => 'x-212.pick-source', 'module' => 'X-212'],
            ['label' => 'Unmatchedfield Map', 'route' => 'x-212.unmatchedfield-map', 'module' => 'X-212'],
            ['label' => 'Dryrun Preview', 'route' => 'x-212.dryrun-preview', 'module' => 'X-212'],
            ['label' => 'Reconciliation Report', 'route' => 'x-212.reconciliation-report', 'module' => 'X-212'],
            ['label' => 'Commit', 'route' => 'x-212.commit', 'module' => 'X-212'],
            ['label' => 'Postimport Audit', 'route' => 'x-212.postimport-audit', 'module' => 'X-212'],
            ['label' => 'Surcharge Line', 'route' => 'x-214.surcharge-line', 'module' => 'X-214'],
            ['label' => 'Surcharge Disclosure', 'route' => 'x-214.surcharge-disclosure', 'module' => 'X-214'],
            ['label' => 'Document Status', 'route' => 'x-215.document-status', 'module' => 'X-215'],
            ['label' => 'Signature Pad', 'route' => 'x-215.signature-pad', 'module' => 'X-215'],
            ['label' => 'Comment Thread', 'route' => 'x-215.comment-thread', 'module' => 'X-215'],
            ['label' => 'Roster Admin', 'route' => 'x-219.roster-admin', 'module' => 'X-219'],
            ['label' => 'Assignment Matrix', 'route' => 'x-219.assignment-matrix', 'module' => 'X-219'],
            ['label' => 'Prompt History', 'route' => 'x-220.prompt-history', 'module' => 'X-220'],
            ['label' => 'Eval Report', 'route' => 'x-220.eval-report', 'module' => 'X-220'],
        ],
        'Money' => [
            ['label' => 'Credits', 'route' => 'c-billing.credits', 'module' => 'C-Billing'],
            ['label' => 'Mrr', 'route' => 'c-billing.mrr', 'module' => 'C-Billing'],
            ['label' => 'Revenue Recovery', 'route' => 'c-billing.revenue-recovery', 'module' => 'C-Billing'],
            ['label' => 'Dunning Board', 'route' => 'c-billing.dunning-board', 'module' => 'C-Billing'],
            ['label' => 'Card Screen', 'route' => 'x-120.card-screen', 'module' => 'X-120'],
            ['label' => 'Margin By Job', 'route' => 'x-166.margin-by-job', 'module' => 'X-166'],
            ['label' => 'By Tech', 'route' => 'x-166.by-tech', 'module' => 'X-166'],
            ['label' => 'By Service', 'route' => 'x-166.by-service', 'module' => 'X-166'],
            ['label' => 'By Source', 'route' => 'x-166.by-source', 'module' => 'X-166'],
            ['label' => 'Stock By Van', 'route' => 'x-167.stock-by-van', 'module' => 'X-167'],
            ['label' => 'Reorders', 'route' => 'x-167.reorders', 'module' => 'X-167'],
            ['label' => 'Commissions', 'route' => 'x-170.commissions', 'module' => 'X-170'],
            ['label' => 'Scorecard', 'route' => 'x-170.scorecard', 'module' => 'X-170'],
            ['label' => 'Dispute Card', 'route' => 'x-201.dispute-card', 'module' => 'X-201'],
            ['label' => 'Dispute Queue', 'route' => 'x-201.dispute-queue', 'module' => 'X-201'],
        ],
        'Calls/Inbox' => [
            ['label' => 'Dns Card', 'route' => 'c-mail.dns-card', 'module' => 'C-Mail'],
            ['label' => 'Sequence View', 'route' => 'c-mail.sequence-view', 'module' => 'C-Mail'],
            ['label' => 'Warmup Calendars Per', 'route' => 'c-mail.warmup-calendars-per', 'module' => 'C-Mail'],
            ['label' => 'Complaintbounce Board', 'route' => 'c-mail.complaintbounce-board', 'module' => 'C-Mail'],
            ['label' => 'Thread', 'route' => 'c-sms.thread', 'module' => 'C-Sms'],
            ['label' => 'Composer Segment Warning', 'route' => 'c-sms.composer-segment-warning', 'module' => 'C-Sms'],
            ['label' => 'Donottext List', 'route' => 'c-sms.donottext-list', 'module' => 'C-Sms'],
            ['label' => 'Pernumber Complaint Monitoring', 'route' => 'c-sms.pernumber-complaint-monitoring', 'module' => 'C-Sms'],
            ['label' => 'Carrier Roster Health', 'route' => 'c-telephony.carrier-roster-health', 'module' => 'C-Telephony'],
            ['label' => 'Failover Log', 'route' => 'c-telephony.failover-log', 'module' => 'C-Telephony'],
            ['label' => 'Thread', 'route' => 'c-whatsapp.thread', 'module' => 'C-Whatsapp'],
            ['label' => 'Template Status Card', 'route' => 'c-whatsapp.template-status-card', 'module' => 'C-Whatsapp'],
            ['label' => 'Template Approval Queue', 'route' => 'c-whatsapp.template-approval-queue', 'module' => 'C-Whatsapp'],
            ['label' => 'Customerfacing Widget', 'route' => 'x-102.customerfacing-widget', 'module' => 'X-102'],
            ['label' => 'Thread', 'route' => 'x-102.thread', 'module' => 'X-102'],
            ['label' => 'Offline Form Inbox', 'route' => 'x-102.offline-form-inbox', 'module' => 'X-102'],
            ['label' => 'Rageclick Rate', 'route' => 'x-102.rageclick-rate', 'module' => 'X-102'],
            ['label' => 'Canvas', 'route' => 'x-125.canvas', 'module' => 'X-125'],
            ['label' => 'Runs', 'route' => 'x-125.runs', 'module' => 'X-125'],
            ['label' => 'Flow Error Dashboard', 'route' => 'x-125.flow-error-dashboard', 'module' => 'X-125'],
            ['label' => 'Attribution Row', 'route' => 'x-137.attribution-row', 'module' => 'X-137'],
            ['label' => 'Dni Pool Utilisation', 'route' => 'x-137.dni-pool-utilisation', 'module' => 'X-137'],
            ['label' => 'Alert Reply By', 'route' => 'x-153.alert-reply-by', 'module' => 'X-153'],
            ['label' => 'Alert Roster Screen', 'route' => 'x-153.alert-roster-screen', 'module' => 'X-153'],
            ['label' => 'Claimexpiry Rate', 'route' => 'x-153.claimexpiry-rate', 'module' => 'X-153'],
            ['label' => 'Your Number Card', 'route' => 'x-188.your-number-card', 'module' => 'X-188'],
            ['label' => 'Pool Inventory', 'route' => 'x-188.pool-inventory', 'module' => 'X-188'],
            ['label' => 'Park List', 'route' => 'x-188.park-list', 'module' => 'X-188'],
            ['label' => 'Pernumber Complaint Board', 'route' => 'x-188.pernumber-complaint-board', 'module' => 'X-188'],
            ['label' => 'Any View It', 'route' => 'x-194.any-view-it', 'module' => 'X-194'],
            ['label' => 'Saved Views List', 'route' => 'x-194.saved-views-list', 'module' => 'X-194'],
            ['label' => 'Agent Desktop', 'route' => 'x-200.agent-desktop', 'module' => 'X-200'],
            ['label' => 'Campaign Board', 'route' => 'x-200.campaign-board', 'module' => 'X-200'],
            ['label' => 'Wallboard', 'route' => 'x-200.wallboard', 'module' => 'X-200'],
            ['label' => 'Qa Scorecard', 'route' => 'x-200.qa-scorecard', 'module' => 'X-200'],
            ['label' => 'Customerfacing None', 'route' => 'x-200.customerfacing-none', 'module' => 'X-200'],
            ['label' => 'Abandonment Complaint Rates', 'route' => 'x-200.abandonment-complaint-rates', 'module' => 'X-200'],
            ['label' => 'Calls', 'route' => 'x-66.calls', 'module' => 'X-66'],
            ['label' => 'Livecoaching Whisper Panel', 'route' => 'x-66.livecoaching-whisper-panel', 'module' => 'X-66'],
            ['label' => 'Customerfacing Call Itself', 'route' => 'x-66.customerfacing-call-itself', 'module' => 'X-66'],
            ['label' => 'Latency P50P95 Per', 'route' => 'x-66.latency-p50p95-per', 'module' => 'X-66'],
        ],
        'Reviews & QA' => [
            ['label' => 'Reviews Qa Requests', 'route' => 'c-reviews.reviews-qa-requests', 'module' => 'C-Reviews'],
            ['label' => 'Qa Report', 'route' => 'c-reviews.qa-report', 'module' => 'C-Reviews'],
            ['label' => 'Tickets', 'route' => 'c-reviews.tickets', 'module' => 'C-Reviews'],
            ['label' => 'Loss Alerts', 'route' => 'c-reviews.loss-alerts', 'module' => 'C-Reviews'],
            ['label' => 'Qa Queue Sladueat', 'route' => 'x-181.qa-queue-sladueat', 'module' => 'X-181'],
            ['label' => 'Ticket', 'route' => 'x-181.ticket', 'module' => 'X-181'],
            ['label' => 'Resolution', 'route' => 'x-181.resolution', 'module' => 'X-181'],
        ],
        'Customers/Inbox' => [
            ['label' => 'Thread', 'route' => 'x-01.thread', 'module' => 'X-01'],
            ['label' => 'Customers List', 'route' => 'x-01.customers-list', 'module' => 'X-01'],
            ['label' => 'Person', 'route' => 'x-01.person', 'module' => 'X-01'],
            ['label' => 'History', 'route' => 'x-01.history', 'module' => 'X-01'],
            ['label' => 'Payment Risk', 'route' => 'x-01.payment-risk', 'module' => 'X-01'],
            ['label' => 'Forecast Risk Tiles', 'route' => 'x-07.forecast-risk-tiles', 'module' => 'X-07'],
            ['label' => 'Risk List', 'route' => 'x-08.risk-list', 'module' => 'X-08'],
            ['label' => 'Sorted', 'route' => 'x-08.sorted', 'module' => 'X-08'],
            ['label' => 'Reason Per Row', 'route' => 'x-08.reason-per-row', 'module' => 'X-08'],
            ['label' => 'Routing Rules', 'route' => 'x-10.routing-rules', 'module' => 'X-10'],
            ['label' => 'Territory Map', 'route' => 'x-10.territory-map', 'module' => 'X-10'],
            ['label' => 'Unassigned Count', 'route' => 'x-10.unassigned-count', 'module' => 'X-10'],
            ['label' => 'Calendar', 'route' => 'x-108.calendar', 'module' => 'X-108'],
            ['label' => 'Waitlist', 'route' => 'x-108.waitlist', 'module' => 'X-108'],
            ['label' => 'Dispatch Board', 'route' => 'x-162.dispatch-board', 'module' => 'X-162'],
            ['label' => 'Map', 'route' => 'x-162.map', 'module' => 'X-162'],
        ],
        'Website' => [
            ['label' => 'Plugin Settings Page', 'route' => 'x-104.plugin-settings-page', 'module' => 'X-104'],
            ['label' => 'Install Count', 'route' => 'x-104.install-count', 'module' => 'X-104'],
            ['label' => 'Migration Card', 'route' => 'x-129.migration-card', 'module' => 'X-129'],
            ['label' => 'Cutover Queue', 'route' => 'x-129.cutover-queue', 'module' => 'X-129'],
            ['label' => 'Forms', 'route' => 'x-155.forms', 'module' => 'X-155'],
            ['label' => 'Submissions Thread', 'route' => 'x-155.submissions-thread', 'module' => 'X-155'],
            ['label' => 'Spam Rate', 'route' => 'x-155.spam-rate', 'module' => 'X-155'],
            ['label' => 'Site Editor Assistant', 'route' => 'x-178.site-editor-assistant', 'module' => 'X-178'],
        ],
        'Visitors' => [
            ['label' => 'Visitors Live', 'route' => 'x-110.visitors-live', 'module' => 'X-110'],
            ['label' => 'Today', 'route' => 'x-110.today', 'module' => 'X-110'],
            ['label' => 'Cooling', 'route' => 'x-110.cooling', 'module' => 'X-110'],
            ['label' => 'Abandoned Forms', 'route' => 'x-110.abandoned-forms', 'module' => 'X-110'],
            ['label' => 'Install Verify', 'route' => 'x-110.install-verify', 'module' => 'X-110'],
            ['label' => 'Tag Version Per', 'route' => 'x-110.tag-version-per', 'module' => 'X-110'],
            ['label' => 'Interest Tags', 'route' => 'x-131.interest-tags', 'module' => 'X-131'],
            ['label' => 'Person Timeline', 'route' => 'x-132.person-timeline', 'module' => 'X-132'],
            ['label' => 'Resolution Rate Confidence', 'route' => 'x-132.resolution-rate-confidence', 'module' => 'X-132'],
            ['label' => 'Attribution Row', 'route' => 'x-138.attribution-row', 'module' => 'X-138'],
            ['label' => 'Roi Dashboard', 'route' => 'x-138.roi-dashboard', 'module' => 'X-138'],
            ['label' => 'Adaccount Connect Card', 'route' => 'x-139.adaccount-connect-card', 'module' => 'X-139'],
            ['label' => 'Conversions Pushed Tile', 'route' => 'x-139.conversions-pushed-tile', 'module' => 'X-139'],
            ['label' => 'Rejection Rate', 'route' => 'x-139.rejection-rate', 'module' => 'X-139'],
            ['label' => 'Counterfactual View', 'route' => 'x-141.counterfactual-view', 'module' => 'X-141'],
            ['label' => 'Replay Runtime Cost', 'route' => 'x-141.replay-runtime-cost', 'module' => 'X-141'],
        ],
        'Home' => [
            ['label' => 'Day One Signup', 'route' => 'x-118.day-one-signup', 'module' => 'X-118'],
            ['label' => 'Groundcheck', 'route' => 'x-118.groundcheck', 'module' => 'X-118'],
            ['label' => 'Test Call', 'route' => 'x-118.test-call', 'module' => 'X-118'],
            ['label' => 'Today', 'route' => 'x-118.today', 'module' => 'X-118'],
            ['label' => 'Same Flow', 'route' => 'x-118.same-flow', 'module' => 'X-118'],
            ['label' => 'Ttfm Distribution', 'route' => 'x-118.ttfm-distribution', 'module' => 'X-118'],
        ],
        'Pricebook' => [
            ['label' => 'Pricebook', 'route' => 'x-163.pricebook', 'module' => 'X-163'],
            ['label' => 'Confirmation Screen', 'route' => 'x-163.confirmation-screen', 'module' => 'X-163'],
            ['label' => 'Daily Pricing Digest', 'route' => 'x-163.daily-pricing-digest', 'module' => 'X-163'],
            ['label' => 'Plans', 'route' => 'x-165.plans', 'module' => 'X-165'],
            ['label' => 'Members', 'route' => 'x-165.members', 'module' => 'X-165'],
        ],
        'Jobs & dispatch' => [
            ['label' => 'Customerfacing Portal', 'route' => 'x-172.customerfacing-portal', 'module' => 'X-172'],
            ['label' => 'Connection Mapping', 'route' => 'x-173.connection-mapping', 'module' => 'X-173'],
            ['label' => 'Conflicts List', 'route' => 'x-173.conflicts-list', 'module' => 'X-173'],
            ['label' => 'Sync Error Rate', 'route' => 'x-173.sync-error-rate', 'module' => 'X-173'],
            ['label' => 'Stafffacing Assistant Panel', 'route' => 'x-175.stafffacing-assistant-panel', 'module' => 'X-175'],
            ['label' => 'Customerfacing None', 'route' => 'x-175.customerfacing-none', 'module' => 'X-175'],
            ['label' => 'By Design', 'route' => 'x-175.by-design', 'module' => 'X-175'],
        ],
        'Marketing' => [
            ['label' => 'Pack Browser', 'route' => 'x-180.pack-browser', 'module' => 'X-180'],
            ['label' => 'Connected Accounts', 'route' => 'x-182.connected-accounts', 'module' => 'X-182'],
            ['label' => 'Social Queue', 'route' => 'x-182.social-queue', 'module' => 'X-182'],
            ['label' => 'Draft Review', 'route' => 'x-183.draft-review', 'module' => 'X-183'],
            ['label' => 'Gate Rejection Reasons', 'route' => 'x-183.gate-rejection-reasons', 'module' => 'X-183'],
            ['label' => 'Content Week', 'route' => 'x-184.content-week', 'module' => 'X-184'],
            ['label' => 'Calendar', 'route' => 'x-184.calendar', 'module' => 'X-184'],
            ['label' => 'Digest Line', 'route' => 'x-185.digest-line', 'module' => 'X-185'],
            ['label' => 'Experiment Board', 'route' => 'x-185.experiment-board', 'module' => 'X-185'],
            ['label' => 'Sequence Builder', 'route' => 'x-186.sequence-builder', 'module' => 'X-186'],
            ['label' => 'Audience Preview Count', 'route' => 'x-186.audience-preview-count', 'module' => 'X-186'],
            ['label' => 'Live Run', 'route' => 'x-186.live-run', 'module' => 'X-186'],
            ['label' => 'Stop Log', 'route' => 'x-186.stop-log', 'module' => 'X-186'],
            ['label' => 'Brand Card Editor', 'route' => 'x-189.brand-card-editor', 'module' => 'X-189'],
            ['label' => 'Preview Per Destination', 'route' => 'x-189.preview-per-destination', 'module' => 'X-189'],
            ['label' => 'Slot Board', 'route' => 'x-190.slot-board', 'module' => 'X-190'],
            ['label' => 'Network Map', 'route' => 'x-190.network-map', 'module' => 'X-190'],
            ['label' => 'Pool Depth Per', 'route' => 'x-190.pool-depth-per', 'module' => 'X-190'],
            ['label' => 'Links Earned', 'route' => 'x-191.links-earned', 'module' => 'X-191'],
            ['label' => 'Pitchacquire Ratio', 'route' => 'x-191.pitchacquire-ratio', 'module' => 'X-191'],
            ['label' => 'Memberships List', 'route' => 'x-192.memberships-list', 'module' => 'X-192'],
        ],
    ],
    'operator' => [
        'Customers/Inbox' => [
            ['label' => 'Routing Rules', 'route' => 'x-10.routing-rules', 'module' => 'X-10'],
            ['label' => 'Territory Map', 'route' => 'x-10.territory-map', 'module' => 'X-10'],
            ['label' => 'Unassigned Count', 'route' => 'x-10.unassigned-count', 'module' => 'X-10'],
        ],
        'Calls/Inbox' => [
            ['label' => 'Customerfacing Widget', 'route' => 'x-102.customerfacing-widget', 'module' => 'X-102'],
            ['label' => 'Thread', 'route' => 'x-102.thread', 'module' => 'X-102'],
            ['label' => 'Offline Form Inbox', 'route' => 'x-102.offline-form-inbox', 'module' => 'X-102'],
            ['label' => 'Rageclick Rate', 'route' => 'x-102.rageclick-rate', 'module' => 'X-102'],
            ['label' => 'Chat Dock Every', 'route' => 'x-124.chat-dock-every', 'module' => 'X-124'],
            ['label' => 'Preview Card', 'route' => 'x-124.preview-card', 'module' => 'X-124'],
            ['label' => 'Todays Recommendation Strip', 'route' => 'x-124.todays-recommendation-strip', 'module' => 'X-124'],
            ['label' => 'Assistantunsupported Log', 'route' => 'x-124.assistantunsupported-log', 'module' => 'X-124'],
            ['label' => 'Canvas', 'route' => 'x-125.canvas', 'module' => 'X-125'],
            ['label' => 'Runs', 'route' => 'x-125.runs', 'module' => 'X-125'],
            ['label' => 'Flow Error Dashboard', 'route' => 'x-125.flow-error-dashboard', 'module' => 'X-125'],
            ['label' => 'Attribution Row', 'route' => 'x-137.attribution-row', 'module' => 'X-137'],
            ['label' => 'Dni Pool Utilisation', 'route' => 'x-137.dni-pool-utilisation', 'module' => 'X-137'],
            ['label' => 'Degrade Rate Per', 'route' => 'x-147.degrade-rate-per', 'module' => 'X-147'],
            ['label' => 'Alert Reply By', 'route' => 'x-153.alert-reply-by', 'module' => 'X-153'],
            ['label' => 'Alert Roster Screen', 'route' => 'x-153.alert-roster-screen', 'module' => 'X-153'],
            ['label' => 'Claimexpiry Rate', 'route' => 'x-153.claimexpiry-rate', 'module' => 'X-153'],
            ['label' => 'Your Number Card', 'route' => 'x-188.your-number-card', 'module' => 'X-188'],
            ['label' => 'Pool Inventory', 'route' => 'x-188.pool-inventory', 'module' => 'X-188'],
            ['label' => 'Park List', 'route' => 'x-188.park-list', 'module' => 'X-188'],
            ['label' => 'Pernumber Complaint Board', 'route' => 'x-188.pernumber-complaint-board', 'module' => 'X-188'],
            ['label' => 'Sendsbyclass', 'route' => 'x-193.sendsbyclass', 'module' => 'X-193'],
            ['label' => 'Quiethour Holds', 'route' => 'x-193.quiethour-holds', 'module' => 'X-193'],
            ['label' => 'Margin Board', 'route' => 'x-197.margin-board', 'module' => 'X-197'],
            ['label' => 'Agent Desktop', 'route' => 'x-200.agent-desktop', 'module' => 'X-200'],
            ['label' => 'Campaign Board', 'route' => 'x-200.campaign-board', 'module' => 'X-200'],
            ['label' => 'Wallboard', 'route' => 'x-200.wallboard', 'module' => 'X-200'],
            ['label' => 'Qa Scorecard', 'route' => 'x-200.qa-scorecard', 'module' => 'X-200'],
            ['label' => 'Customerfacing None', 'route' => 'x-200.customerfacing-none', 'module' => 'X-200'],
            ['label' => 'Abandonment Complaint Rates', 'route' => 'x-200.abandonment-complaint-rates', 'module' => 'X-200'],
            ['label' => 'Calls', 'route' => 'x-66.calls', 'module' => 'X-66'],
            ['label' => 'Livecoaching Whisper Panel', 'route' => 'x-66.livecoaching-whisper-panel', 'module' => 'X-66'],
            ['label' => 'Customerfacing Call Itself', 'route' => 'x-66.customerfacing-call-itself', 'module' => 'X-66'],
            ['label' => 'Latency P50P95 Per', 'route' => 'x-66.latency-p50p95-per', 'module' => 'X-66'],
        ],
        'Website' => [
            ['label' => 'Plugin Settings Page', 'route' => 'x-104.plugin-settings-page', 'module' => 'X-104'],
            ['label' => 'Install Count', 'route' => 'x-104.install-count', 'module' => 'X-104'],
            ['label' => 'Migration Card', 'route' => 'x-129.migration-card', 'module' => 'X-129'],
            ['label' => 'Cutover Queue', 'route' => 'x-129.cutover-queue', 'module' => 'X-129'],
            ['label' => 'Forms', 'route' => 'x-155.forms', 'module' => 'X-155'],
            ['label' => 'Submissions Thread', 'route' => 'x-155.submissions-thread', 'module' => 'X-155'],
            ['label' => 'Spam Rate', 'route' => 'x-155.spam-rate', 'module' => 'X-155'],
            ['label' => 'Edge Status Per', 'route' => 'x-157.edge-status-per', 'module' => 'X-157'],
            ['label' => 'Prospecttenantfacing Top3 Preview', 'route' => 'x-179.prospecttenantfacing-top3-preview', 'module' => 'X-179'],
            ['label' => 'Match Scores', 'route' => 'x-179.match-scores', 'module' => 'X-179'],
        ],
        'Marketing' => [
            ['label' => 'Pipeline Board', 'route' => 'x-105.pipeline-board', 'module' => 'X-105'],
            ['label' => 'Submission Log', 'route' => 'x-109.submission-log', 'module' => 'X-109'],
            ['label' => 'Manual Queue', 'route' => 'x-109.manual-queue', 'module' => 'X-109'],
            ['label' => 'Draft Review', 'route' => 'x-183.draft-review', 'module' => 'X-183'],
            ['label' => 'Gate Rejection Reasons', 'route' => 'x-183.gate-rejection-reasons', 'module' => 'X-183'],
            ['label' => 'Digest Line', 'route' => 'x-185.digest-line', 'module' => 'X-185'],
            ['label' => 'Experiment Board', 'route' => 'x-185.experiment-board', 'module' => 'X-185'],
            ['label' => 'Slot Board', 'route' => 'x-190.slot-board', 'module' => 'X-190'],
            ['label' => 'Network Map', 'route' => 'x-190.network-map', 'module' => 'X-190'],
            ['label' => 'Pool Depth Per', 'route' => 'x-190.pool-depth-per', 'module' => 'X-190'],
            ['label' => 'Links Earned', 'route' => 'x-191.links-earned', 'module' => 'X-191'],
            ['label' => 'Pitchacquire Ratio', 'route' => 'x-191.pitchacquire-ratio', 'module' => 'X-191'],
        ],
        'Visitors' => [
            ['label' => 'Visitors Live', 'route' => 'x-110.visitors-live', 'module' => 'X-110'],
            ['label' => 'Today', 'route' => 'x-110.today', 'module' => 'X-110'],
            ['label' => 'Cooling', 'route' => 'x-110.cooling', 'module' => 'X-110'],
            ['label' => 'Abandoned Forms', 'route' => 'x-110.abandoned-forms', 'module' => 'X-110'],
            ['label' => 'Install Verify', 'route' => 'x-110.install-verify', 'module' => 'X-110'],
            ['label' => 'Tag Version Per', 'route' => 'x-110.tag-version-per', 'module' => 'X-110'],
            ['label' => 'Person Timeline', 'route' => 'x-132.person-timeline', 'module' => 'X-132'],
            ['label' => 'Resolution Rate Confidence', 'route' => 'x-132.resolution-rate-confidence', 'module' => 'X-132'],
            ['label' => 'Adaccount Connect Card', 'route' => 'x-139.adaccount-connect-card', 'module' => 'X-139'],
            ['label' => 'Conversions Pushed Tile', 'route' => 'x-139.conversions-pushed-tile', 'module' => 'X-139'],
            ['label' => 'Rejection Rate', 'route' => 'x-139.rejection-rate', 'module' => 'X-139'],
            ['label' => 'Counterfactual View', 'route' => 'x-141.counterfactual-view', 'module' => 'X-141'],
            ['label' => 'Replay Runtime Cost', 'route' => 'x-141.replay-runtime-cost', 'module' => 'X-141'],
        ],
        'Settings' => [
            ['label' => 'Console', 'route' => 'x-111.console', 'module' => 'X-111'],
            ['label' => 'Agency Console', 'route' => 'x-112.agency-console', 'module' => 'X-112'],
            ['label' => 'Staff', 'route' => 'x-112.staff', 'module' => 'X-112'],
            ['label' => 'Roles', 'route' => 'x-112.roles', 'module' => 'X-112'],
            ['label' => 'Impersonation Log', 'route' => 'x-112.impersonation-log', 'module' => 'X-112'],
            ['label' => 'Reviewwhatifound Screen', 'route' => 'x-119.reviewwhatifound-screen', 'module' => 'X-119'],
            ['label' => 'Price Confirmation Screen', 'route' => 'x-119.price-confirmation-screen', 'module' => 'X-119'],
            ['label' => 'Teaching Box', 'route' => 'x-119.teaching-box', 'module' => 'X-119'],
            ['label' => 'Fact Freshness Per', 'route' => 'x-119.fact-freshness-per', 'module' => 'X-119'],
            ['label' => 'Entity History Viewer', 'route' => 'x-121.entity-history-viewer', 'module' => 'X-121'],
            ['label' => 'When X111 Renders', 'route' => 'x-121.when-x111-renders', 'module' => 'X-121'],
            ['label' => 'Action Log', 'route' => 'x-122.action-log', 'module' => 'X-122'],
            ['label' => 'Dlq Request Inspector', 'route' => 'x-123.dlq-request-inspector', 'module' => 'X-123'],
            ['label' => 'Refusal Analytics', 'route' => 'x-126.refusal-analytics', 'module' => 'X-126'],
            ['label' => 'Matrix View', 'route' => 'x-128.matrix-view', 'module' => 'X-128'],
            ['label' => 'Demand Tile', 'route' => 'x-130.demand-tile', 'module' => 'X-130'],
            ['label' => 'Public Index Pages', 'route' => 'x-130.public-index-pages', 'module' => 'X-130'],
            ['label' => 'Coverage By Trade', 'route' => 'x-130.coverage-by-trade', 'module' => 'X-130'],
            ['label' => 'Research Dossier Per', 'route' => 'x-135.research-dossier-per', 'module' => 'X-135'],
            ['label' => 'Cooling', 'route' => 'x-136.cooling', 'module' => 'X-136'],
            ['label' => 'Signal Volume Precision', 'route' => 'x-136.signal-volume-precision', 'module' => 'X-136'],
            ['label' => 'Connect Your Ai', 'route' => 'x-142.connect-your-ai', 'module' => 'X-142'],
            ['label' => 'Webhooks', 'route' => 'x-142.webhooks', 'module' => 'X-142'],
            ['label' => 'Mcp Token Registry', 'route' => 'x-142.mcp-token-registry', 'module' => 'X-142'],
            ['label' => 'Visibility Tile', 'route' => 'x-144.visibility-tile', 'module' => 'X-144'],
            ['label' => 'Question List', 'route' => 'x-144.question-list', 'module' => 'X-144'],
            ['label' => 'Tenant Zeros Own', 'route' => 'x-144.tenant-zeros-own', 'module' => 'X-144'],
            ['label' => 'Proposals Appear Today', 'route' => 'x-145.proposals-appear-today', 'module' => 'X-145'],
            ['label' => 'Retrieval Latency Emptyrate', 'route' => 'x-148.retrieval-latency-emptyrate', 'module' => 'X-148'],
            ['label' => 'Quality Board', 'route' => 'x-149.quality-board', 'module' => 'X-149'],
            ['label' => 'Provider Cost Per', 'route' => 'x-150.provider-cost-per', 'module' => 'X-150'],
            ['label' => 'Fetch Board', 'route' => 'x-151.fetch-board', 'module' => 'X-151'],
            ['label' => 'Connect Source', 'route' => 'x-156.connect-source', 'module' => 'X-156'],
            ['label' => 'Rejectedrows List', 'route' => 'x-156.rejectedrows-list', 'module' => 'X-156'],
            ['label' => 'Ingest Volume By', 'route' => 'x-156.ingest-volume-by', 'module' => 'X-156'],
            ['label' => 'Prospectfacing Video Demo', 'route' => 'x-158.prospectfacing-video-demo', 'module' => 'X-158'],
            ['label' => 'Content Plans Video', 'route' => 'x-158.content-plans-video', 'module' => 'X-158'],
            ['label' => 'Render Queue', 'route' => 'x-158.render-queue', 'module' => 'X-158'],
            ['label' => 'Customerprospectfacing Audit Page', 'route' => 'x-159.customerprospectfacing-audit-page', 'module' => 'X-159'],
            ['label' => 'Score', 'route' => 'x-159.score', 'module' => 'X-159'],
            ['label' => 'Audit Queue', 'route' => 'x-159.audit-queue', 'module' => 'X-159'],
            ['label' => 'Geogrid Map', 'route' => 'x-16.geogrid-map', 'module' => 'X-16'],
            ['label' => 'Servicearea Polygon', 'route' => 'x-16.servicearea-polygon', 'module' => 'X-16'],
            ['label' => 'Harvest Coverage By', 'route' => 'x-16.harvest-coverage-by', 'module' => 'X-16'],
            ['label' => 'Upload Drop', 'route' => 'x-160.upload-drop', 'module' => 'X-160'],
            ['label' => 'Review Screen', 'route' => 'x-160.review-screen', 'module' => 'X-160'],
            ['label' => 'Extraction Error Rate', 'route' => 'x-160.extraction-error-rate', 'module' => 'X-160'],
            ['label' => 'Demo Ledger Daily', 'route' => 'x-161.demo-ledger-daily', 'module' => 'X-161'],
            ['label' => 'Gbp Card', 'route' => 'x-177.gbp-card', 'module' => 'X-177'],
            ['label' => 'Suspensionrisk Events Fleetwide', 'route' => 'x-177.suspensionrisk-events-fleetwide', 'module' => 'X-177'],
            ['label' => 'Marketplace', 'route' => 'x-195.marketplace', 'module' => 'X-195'],
            ['label' => 'Manifest Review Queue', 'route' => 'x-195.manifest-review-queue', 'module' => 'X-195'],
            ['label' => 'Extension Popup', 'route' => 'x-196.extension-popup', 'module' => 'X-196'],
            ['label' => 'Connect Card', 'route' => 'x-198.connect-card', 'module' => 'X-198'],
            ['label' => 'Same Account', 'route' => 'x-198.same-account', 'module' => 'X-198'],
            ['label' => 'Reconciliation Discrepancies', 'route' => 'x-198.reconciliation-discrepancies', 'module' => 'X-198'],
            ['label' => 'Refusals By Reason', 'route' => 'x-204.refusals-by-reason', 'module' => 'X-204'],
            ['label' => 'Register Slot States', 'route' => 'x-204.register-slot-states', 'module' => 'X-204'],
            ['label' => 'One Confirmonce Toggle', 'route' => 'x-207.one-confirmonce-toggle', 'module' => 'X-207'],
            ['label' => 'Promptcopy Editor', 'route' => 'x-207.promptcopy-editor', 'module' => 'X-207'],
            ['label' => 'Retirement Reasons', 'route' => 'x-207.retirement-reasons', 'module' => 'X-207'],
            ['label' => 'Perplatform Delivery Health', 'route' => 'x-207.perplatform-delivery-health', 'module' => 'X-207'],
        ],
        'Home' => [
            ['label' => 'Day One Signup', 'route' => 'x-118.day-one-signup', 'module' => 'X-118'],
            ['label' => 'Groundcheck', 'route' => 'x-118.groundcheck', 'module' => 'X-118'],
            ['label' => 'Test Call', 'route' => 'x-118.test-call', 'module' => 'X-118'],
            ['label' => 'Today', 'route' => 'x-118.today', 'module' => 'X-118'],
            ['label' => 'Same Flow', 'route' => 'x-118.same-flow', 'module' => 'X-118'],
            ['label' => 'Ttfm Distribution', 'route' => 'x-118.ttfm-distribution', 'module' => 'X-118'],
        ],
        'Jobs & dispatch' => [
            ['label' => 'Stafffacing App', 'route' => 'x-171.stafffacing-app', 'module' => 'X-171'],
            ['label' => 'Sync Failure Rate', 'route' => 'x-171.sync-failure-rate', 'module' => 'X-171'],
            ['label' => 'Connection Mapping', 'route' => 'x-173.connection-mapping', 'module' => 'X-173'],
            ['label' => 'Conflicts List', 'route' => 'x-173.conflicts-list', 'module' => 'X-173'],
            ['label' => 'Sync Error Rate', 'route' => 'x-173.sync-error-rate', 'module' => 'X-173'],
        ],
        'Money' => [
            ['label' => 'Dispute Card', 'route' => 'x-201.dispute-card', 'module' => 'X-201'],
            ['label' => 'Dispute Queue', 'route' => 'x-201.dispute-queue', 'module' => 'X-201'],
            ['label' => 'Rate Registry', 'route' => 'x-82.rate-registry', 'module' => 'X-82'],
        ],
    ],
    'agency' => [
        'Settings' => [
            ['label' => 'Agency Console', 'route' => 'x-112.agency-console', 'module' => 'X-112'],
            ['label' => 'Staff', 'route' => 'x-112.staff', 'module' => 'X-112'],
            ['label' => 'Roles', 'route' => 'x-112.roles', 'module' => 'X-112'],
            ['label' => 'Impersonation Log', 'route' => 'x-112.impersonation-log', 'module' => 'X-112'],
            ['label' => 'Connect Card', 'route' => 'x-198.connect-card', 'module' => 'X-198'],
            ['label' => 'Same Account', 'route' => 'x-198.same-account', 'module' => 'X-198'],
            ['label' => 'Reconciliation Discrepancies', 'route' => 'x-198.reconciliation-discrepancies', 'module' => 'X-198'],
        ],
        'Home' => [
            ['label' => 'Day One Signup', 'route' => 'x-118.day-one-signup', 'module' => 'X-118'],
            ['label' => 'Groundcheck', 'route' => 'x-118.groundcheck', 'module' => 'X-118'],
            ['label' => 'Test Call', 'route' => 'x-118.test-call', 'module' => 'X-118'],
            ['label' => 'Today', 'route' => 'x-118.today', 'module' => 'X-118'],
            ['label' => 'Same Flow', 'route' => 'x-118.same-flow', 'module' => 'X-118'],
            ['label' => 'Ttfm Distribution', 'route' => 'x-118.ttfm-distribution', 'module' => 'X-118'],
        ],
    ],
    'tech' => [
    ],
];
