<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 9 capability(ies) for X-121.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-121/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'G4-12' => 'Redis on high-read nouns, invalidated inline on write',

    // status: SPECCED
    'G4-16' => 'RLS FORCEd on every noun table, never optional',

    // status: SPECCED
    'G4-21' => 'read-replica routing at the entity layer; the topology is turn 95\'s',

    // status: SPECCED
    'G4-37' => 'Asset versioning; the ransomware case is turn 93\'s',

    // status: SPECCED
    'G4-42' => 'version restore with a compensable reversal class refuses',

    // status: SPECCED
    'G4-46' => 'Asset history and side-by-side compare',

    // status: SPECCED
    'G4-51' => 'expand/contract on the noun tables; the release switch is Step 8\'s refuses',

    // status: SPECCED
    'G11-14' => 'named in the header — with version restore refuses',

    // status: SPECCED
    'G17-28' => 'field-level history with version restore — named in the header',
];
