<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 7 capability(ies) for X-110.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-110/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'G6-09' => 'UTM survives the session; the attribution is X-138\'s',

    // status: SPECCED
    'G9-02' => 'ClickHouse is corpus vocabulary — one database (§22 · P-143)',

    // status: SPECCED
    'G13-01' => 'the header\'s own shape — first-party, on the tenant\'s subdomain',

    // status: SPECCED
    'G13-12' => 'the chat\'s context updates from the page (X-102)',

    // status: SPECCED
    'G13-27' => 'watching the tenant\'s OWN tags fire is not ad management',

    // status: SPECCED
    'G13-28' => 'the 50ms hop before redirect',

    // status: SPECCED
    'G13-30' => 'rage-click and scroll depth, rendered by X-194',
];
