<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by \`module:scaffold\` from the documented header. DO NOT EDIT.
 *
 * A hand-edited manifest is a manifest that drifts, and every stale-record
 * defect in this programme was a hand-maintained file. Change the header,
 * re-run the scaffold.
 *
 * @module X-110
 *
 * @intent OBSERVE under §227.2
 *
 * @ingress page.loaded <browser>
 */
return [
    'module' => 'X-110',
    'intent' => 'OBSERVE under §227.2',

    // ⛔⛔⛔ R235 — `ships` EQUALS `ceiling`. THE AUTOPILOT IS ON.
    //
    // This comment used to teach §227.2's intent default: "GROW ships
    // L1, PROPOSES ONLY, ALWAYS". The owner struck it — "ALL AI ON, by
    // my law. The client can turn it off if they want."
    //
    // ⭐ There is nothing to earn. @intent still DESCRIBES the action;
    //   it no longer gates when the action may run.
    'ships' => 'n/a',
    'ceiling' => 'L3',

    'provides' => [
        'pixel.install',
        'pixel.verify',
        'pixel.events',
    ],
    'emits' => [
        'visit.started',
        'visit.identified',
        'rage_click.detected',
        'exit_intent.detected',
        'form.abandoned',
        'cwv.measured',
    ],
    'consumes' => [
        'page.loaded',
    ],

    // ⛔ P-163 — @owns_table may not name one of X-121's canonical nouns.
    'owns_table' => [
        'pixel_events',
        'visits',
        'sessions',
        'cwv_samples',
        'identity_links',
    ],
    'reads_table' => [],

    'renders' => [
        'visitors_live',
        'today',
        'cooling',
        'abandoned_forms',
        'install_verify',
        'tag_version_per',
    ],

    // P-209 — silence fails OPEN. `none` is a decision; absence is not.
    'agent_reachable' => [
        'pixel.verify',
        'none',
    ],
];
