<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by \`module:scaffold\` from the documented header. DO NOT EDIT.
 *
 * A hand-edited manifest is a manifest that drifts, and every stale-record
 * defect in this programme was a hand-maintained file. Change the header,
 * re-run the scaffold.
 *
 * @module X-211
 *
 * @intent RECOVER under §227.2
 *
 * @ingress invoice.overdue <clock>
 */
return [
    'module' => 'X-211',
    'intent' => 'RECOVER under §227.2',

    // ⛔⛔⛔ R235 — `ships` EQUALS `ceiling`. THE AUTOPILOT IS ON.
    //
    // This comment used to teach §227.2's intent default: "GROW ships
    // L1, PROPOSES ONLY, ALWAYS". The owner struck it — "ALL AI ON, by
    // my law. The client can turn it off if they want."
    //
    // ⭐ There is nothing to earn. @intent still DESCRIBES the action;
    //   it no longer gates when the action may run.
    'ships' => 'L3',
    'ceiling' => 'L3',

    'provides' => [
        'ar.apply_late_fee',
        'ar.offer_plan',
        'ar.force_ach',
        'ar.log_offline_payment',
        'ar.package_for_collections',
    ],
    'emits' => [
        'ar.overdue',
        'ar.fee_applied',
        'ar.plan_accepted',
        'ar.escalated_to_human',
        'ar.packaged',
    ],
    'consumes' => [
        'invoice.overdue',
    ],

    // ⛔ P-163 — @owns_table may not name one of X-121's canonical nouns.
    'owns_table' => [
        'receivable_states',
        'payment_plans',
        'offline_payments',
    ],
    'reads_table' => [],

    'renders' => [
        'ageing_by_reason',
        'invoice_thread_beside',
        'paymentplan_builder',
        'collections_package_preview',
    ],

    // P-209 — silence fails OPEN. `none` is a decision; absence is not.
    'agent_reachable' => [
        'none',
        'none',
        'none',
    ],
];
