<?php

declare(strict_types=1);

namespace App\Services\Actuation\WordPress;

/**
 * A WordPress Application Password, wrapped so that a stack trace cannot print
 * it.
 *
 * ⛔ **THIS CLASS EXISTS BECAUSE A PHP STACK TRACE PRINTS SCALAR ARGUMENTS AND
 * THIS ONE IS MEASURED RATHER THAN ASSUMED.** `zend.exception_ignore_args` is
 * `0` on this machine, so `Throwable::getTraceAsString()` renders every scalar
 * argument of every frame — truncated to fifteen characters and followed by
 * `...`. An application password is twenty-four alphanumerics generated by
 * `wp_generate_password()`; fifteen of them, printed into a log line or an
 * exception report, is not a partial leak in any useful sense.
 *
 * **An object argument renders as `Object(App\Services\Actuation\WordPress\ApplicationPassword)`
 * and carries nothing**, so the fix is a type rather than a discipline. `$hidden`
 * closes serialization, `WordPressSite::__debugInfo()` closes inspection, and
 * this closes the third path — which was the only one of the three nothing
 * covered.
 *
 * ⚠️ **`zend.exception_ignore_args=1` WOULD ALSO CLOSE IT AND IS NOT THE
 * ANSWER.** It is a php.ini value, so it is a property of a deployment rather
 * than of this code: correct on the production box today, silently absent on a
 * new one, and invisible in review. It is worth setting **as well**.
 *
 * ⛔ **NO `__toString()`, DELIBERATELY.** A `__toString()` would make every
 * accidental interpolation — a log line, an exception message, a URL built with
 * `.` — silently succeed, which is precisely the set of accidents this type is
 * for. Reaching the value takes {@see self::reveal()}, which is one grep away
 * from an audit of every place the secret is in the clear.
 */
final readonly class ApplicationPassword
{
    public function __construct(private string $value) {}

    /**
     * ⚠️ **EVERY CALL TO THIS IS A PLACE THE SECRET IS IN THE CLEAR.** There are
     * two in `app/`: the Basic Auth header, and the encrypted column.
     */
    public function reveal(): string
    {
        return $this->value;
    }

    /**
     * @return array<string, string>
     */
    public function __debugInfo(): array
    {
        return ['value' => '[redacted]'];
    }
}
