<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 16 capability(ies) for X-108.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-108/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'G1-12' => 'tokens only (P-160), the iframe boundary asserted refuses',

    // status: SPECCED
    'G2-04' => 'Google/Outlook calendars; the header already owns Calendly/Eventbrite sync',

    // status: SPECCED
    'G2-06' => 'the agent calls availability.request; time is looked up or refused (P-093)',

    // status: SPECCED
    'G2-10' => 'the calendar half is X-108\'s; the hiring flow is G15\'s',

    // status: SPECCED
    'G2-12' => 'split: the blackout calendar is X-108\'s ("blackouts and holiday overrides"); the PTO request-and-approval workflow is G15\'s',

    // status: SPECCED
    'G2-13' => 'out-of-office is named in the header',

    // status: SPECCED
    'G2-45' => 'the agent offers only a window the scheduler confirmed · refuses: a window the scheduler has not confirmed',

    // status: SPECCED
    'G2-49' => 'named in the header',

    // status: SPECCED
    'G2-58' => 'questions on the booking page refuses',

    // status: SPECCED
    'G15-08' => 'out-of-office is named in the header; X-10 skips an unavailable assignee',

    // status: SPECCED
    'G17-27' => 'slots localised to the customer\'s browser',

    // status: SPECCED
    'G18-07' => 'blackouts and holiday overrides are named in the header',

    // status: SPECCED
    'G18-27' => 'a booking generates its own conference link · refuses: generating a conference link without a booking',

    // status: SPECCED
    'G19-01' => 'named in the header — a cancellation fills itself refuses',

    // status: SPECCED
    'G19-20' => '24h · 1h · 10min;  one segment = one credit, a meter and never a fee',

    // status: SPECCED
    'G15-32' => '',
];
