<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 7 capability(ies) for X-170.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-170/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'G1-16' => 'asserted: no commission is payable until the money is in (the single most common commission dispute in field service)',

    // status: SPECCED
    'G7-03' => 'a projection over commission rules; rendered by X-194',

    // status: SPECCED
    'G7-32' => 'commission on gross profit;  paid on cash COLLECTED, never invoiced',

    // status: SPECCED
    'G7-38' => 'a time-boxed bonus rule refuses',

    // status: SPECCED
    'G7-39' => 'two payees on one deal',

    // status: SPECCED
    'G7-42' => 'staff commission tiers by revenue band',

    // status: SPECCED
    'G9-29' => 'pending · cleared · clawed-back, in real time',
];
