<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 6 capability(ies) for C-Ai.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/C-Ai/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'G2-19' => 'the dispatcher\'s whole job; cost is a routing input, never a quality excuse',

    // status: SPECCED
    'G2-27' => 'the plan\'s mechanism is grounding + lexicon + the teaching box (P-097); a per-tenant fine-tune is an owner question refuses',

    // status: SPECCED
    'G5-22' => 'split: the key is C-Ai\'s;  the MRR-discount half is KILLED (T591 — no discounts)',

    // status: SPECCED
    'G5-44' => 'cost is measured cent-precision in ai_calls',

    // status: SPECCED
    'G5-45' => 'NAME COLLISION — X-150 ProviderWaterfall is the DATA-provider waterfall; model failover is C-Ai\'s',

    // status: SPECCED
    'G10-22' => 'TTFT demotion in the model waterfall',
];
