<?php

namespace Tests\Modules\X103;

use Tests\TestCase;

class AutogeneratedTest extends TestCase
{
    public function test_g6_17()
    { /* G6-17 */
    }

    public function test_g6_20()
    { /* G6-20 */
    }
}
