<?php

namespace Tests\Modules\X103;

use App\Enums\AiModel;
use App\Models\PlatformSetting;
use Tests\TestCase;

class AutogeneratedTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp();
        PlatformSetting::write('ai.model.site_copy', AiModel::Gpt4oMini->value, 'test');
    }

    public function test_g6_17()
    { /* G6-17 */
    }

    public function test_g6_20()
    { /* G6-20 */
    }
}
