<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 8 capability(ies) for X-134.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-134/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'G3-08' => 'a 90-day re-ping; staleness is fetched_at, never an eviction (P-143)',

    // status: SPECCED
    'G3-19' => 'tech-stack enrichment with source and confidence',

    // status: SPECCED
    'G3-50' => 'the domain\'s own summary line; = X-151 + X-134',

    // status: SPECCED
    'G3-51' => 'with source and confidence',

    // status: SPECCED
    'G3-57' => 'Wappalyzer as one waterfall rung',

    // status: SPECCED
    'G3-65' => 'named in the header',

    // status: SPECCED
    'G3-66' => '= G3-65; one spec',

    // status: SPECCED
    'G13-26' => 'a prospect\'s installed pixels as an enrichment field',
];
