<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 7 capability(ies) for X-128.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-128/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'N-050' => 'refuses NO_FACT',

    // status: SPECCED
    'N-051' => 'refuses NO_FACT',

    // status: SPECCED
    'N-053' => 'it reads every module\'s declarations and FAILS THE BUILD on a consumed event with no origin (P-208/P-213 — this module IS gate 6) · it never writes to a module · its output is regenerated, never hand-edited',

    // status: SPECCED
    'N-054' => 'refuses NO_FACT',

    // status: SPECCED
    'N-055' => 'it reads every module\'s declarations and FAILS THE BUILD on a consumed event with no origin (P-208/P-213 — this module IS gate 6) · it never writes to a module · its output is regenerated, never hand-edited',

    // status: SPECCED
    'N-057' => 'refuses NO_FACT',

    // status: SPECCED
    'N-060' => 'refuses NO_FACT',
];
