<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 22 capability(ies) for X-158.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-158/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'G3-22' => 'the name is a Fact, never a guess',

    // status: SPECCED
    'G3-25' => 'a watch threshold is a signal; the send is X-105\'s',

    // status: SPECCED
    'G3-46' => 'an expiring short link (P-072)',

    // status: SPECCED
    'G5-02' => 'refuses to extract action items from videos that contain no spoken dialogue, returning an empty set instead of hallucinated tasks.',

    // status: SPECCED
    'G5-52' => 'video tone → written tone',

    // status: SPECCED
    'G8-37' => 'show-notes rewriting — spec with the video pass (turn 32)',

    // status: SPECCED
    'G9-30' => 'watch-depth as a signal, never a permit (P-068)',

    // status: SPECCED
    'G11-27' => 'refuses to generate a promo email draft if the source episode lacks a defined title or transcript, ensuring valid context.',

    // status: SPECCED
    'G12-06' => 'refuses to auto-publish an episode without explicit manual approval of the generated show notes by a publisher role.',

    // status: SPECCED
    'G12-22' => 'episode furniture — the video pass',

    // status: SPECCED
    'G12-23' => 'refuses to generate instant show notes if the transcript confidence score is below 70%, preventing poorly summarized content.',

    // status: SPECCED
    'G12-24' => 'a video summarised into slides',

    // status: SPECCED
    'G12-34' => 'refuses to create social snippets containing explicit or offensive language found in the transcript, flagging them for review.',

    // status: SPECCED
    'G12-37' => 'transcript → thread',

    // status: SPECCED
    'G16-02' => 'burned captions on the 90-second cut',

    // status: SPECCED
    'G16-06' => 'ad PACKS as content are not fenced (P-128)',

    // status: SPECCED
    'G16-14' => 'the branch is a state on the Conversation',

    // status: SPECCED
    'G16-22' => 'three cuts from the long form',

    // status: SPECCED
    'G16-23' => 'topic changes detected in the audio',

    // status: SPECCED
    'G16-30' => 'refuses to generate a VSL script if the five required prerequisite questions are not fully answered, avoiding invented statistics.',

    // status: SPECCED
    'G18-26' => 'live webinar rooms and tokens',

    // status: SPECCED
    'G16-32' => '§226.4 · P-202 — the disclosure is rendered IN the frame, not only in metadata · transcribed from the plan 2026-08-27 · ⛔ register description STRIPPED (P-206) — it lives in the register, not in the file the brief reads · ⑤ the disclosure is rendered IN THE FRAME — asserted on the output file, not the request',
];
