<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 5 capability(ies) for C-Telephony.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/C-Telephony/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'G11-36' => 'carrier-side screening before we pay for the minute refuses',

    // status: SPECCED
    'G11-39' => 'SHAKEN/STIR grading on inbound refuses',

    // status: SPECCED
    'G18-18' => 'the router and the eight adapters are the header refuses',

    // status: SPECCED
    'G18-20' => 'LTV read from C-Billing; the bypass is a routing rule refuses',

    // status: SPECCED
    'G19-03' => 'T677 (owner) — we do not route around carriers, and P-070: a thread keeps its carrier; migration happens on hard failure, never for cost',
];
