<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by \`module:scaffold\` from the documented header. DO NOT EDIT.
 *
 * A hand-edited manifest is a manifest that drifts, and every stale-record
 * defect in this programme was a hand-maintained file. Change the header,
 * re-run the scaffold.
 *
 * @module X-163
 *
 * @intent NONE under §227.2
 *
 * @ingress agent.refused <system>
 */
return [
    'module' => 'X-163',
    'intent' => 'NONE under §227.2',

    // ⛔⛔⛔ R235 — `ships` EQUALS `ceiling`. THE AUTOPILOT IS ON.
    //
    // This comment used to teach §227.2's intent default: "GROW ships
    // L1, PROPOSES ONLY, ALWAYS". The owner struck it — "ALL AI ON, by
    // my law. The client can turn it off if they want."
    //
    // ⭐ There is nothing to earn. @intent still DESCRIBES the action;
    //   it no longer gates when the action may run.
    'ships' => 'n/a',
    'ceiling' => 'L3',

    'provides' => [
        'price.lookup',
        'price.confirm',
        'price.range',
        'callout.lookup',
        'book.version',
    ],
    'emits' => [
        'pricebook.updated',
        'price.confirmed',
        'version.bumped',
        'price.refusal_flagged',
    ],
    'consumes' => [
        'document.ingested',
        'job.completed',
        'agent.refused',
    ],

    // ⛔ P-163 — @owns_table may not name one of X-121's canonical nouns.
    'owns_table' => [
        'price_book_items',
        'price_book_versions',
        'location_books',
        'callout_fees',
    ],
    'reads_table' => [],

    'renders' => [
        'pricebook',
        'confirmation_screen',
        'daily_pricing_digest',
    ],

    // P-209 — silence fails OPEN. `none` is a decision; absence is not.
    'agent_reachable' => [
        'none',
        'none',
        'none',
    ],
];
