<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 15 capability(ies) for C-Reviews.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/C-Reviews/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'G18-14' => 'CSAT on resolve is named in the header refuses',

    // status: SPECCED
    'G19-10' => 'compose-time block on "review for 10% off" — review-gating incentives are banned on every class, and this is the lint that enforces it',

    // status: SPECCED
    'G20-01' => 'P-110 — 1–3★ never reaches a public reply path, which is exactly what makes auto-reply structurally safe',

    // status: SPECCED
    'G20-03' => 'the prompt lint: "how did the repair go", never "mention Dave" (§37.3)',

    // status: SPECCED
    'G20-04' => 'named in the header;  a reviewer\'s name is a signal — contacting them needs a Lane-2 basis they have not given (P-068)',

    // status: SPECCED
    'G20-05' => 'CSAT on resolve; a 1★ reopens the ticket in X-111',

    // status: SPECCED
    'G20-06' => 'named in the header',

    // status: SPECCED
    'G20-07' => 'day 60, <7 → triage (P-113)',

    // status: SPECCED
    'G20-08' => 'named in the header — Google via Zernio · Yelp · Facebook · BBB',

    // status: SPECCED
    'G20-09' => 'the owner\'s original ask, now the header',

    // status: SPECCED
    'G20-11' => 'P-110 supersedes the legacy review gate as the MECHANISM: every request is triaged, low ratings become a ticket with an SLA, high ratings are asked publicly. The register\'s wording is the old gate\'s name.  keep-gate is still an open reverse word — the owner\'s, not the audit\'s',

    // status: SPECCED
    'G20-12' => '= Review Gating; one spec, under P-110',

    // status: SPECCED
    'G20-13' => 'named in the header; the send is Marketing class and waits for the window',

    // status: SPECCED
    'G20-14' => 'anything ambiguous is DRAFTED to the inbox, never published — sarcasm read as praise is a brand disaster (§149.1)',

    // status: SPECCED
    'G1-68' => '',
];
