<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by \`module:scaffold\` from the documented header. DO NOT EDIT.
 *
 * A hand-edited manifest is a manifest that drifts, and every stale-record
 * defect in this programme was a hand-maintained file. Change the header,
 * re-run the scaffold.
 *
 * @module C-Reviews
 *
 * @intent GROW under §227.2
 */
return [
    'module' => 'C-Reviews',
    'intent' => 'GROW under §227.2',

    // ⛔⛔⛔ R235 — `ships` EQUALS `ceiling`. THE AUTOPILOT IS ON.
    //
    // This comment used to teach §227.2's intent default: "GROW ships
    // L1, PROPOSES ONLY, ALWAYS". The owner struck it — "ALL AI ON, by
    // my law. The client can turn it off if they want."
    //
    // ⭐ There is nothing to earn. @intent still DESCRIBES the action;
    //   it no longer gates when the action may run.
    'ships' => 'L2',
    'ceiling' => 'L2',

    'provides' => [
        'review.request',
        'review.reply',
        'review.sync',
        'qa.ticket',
    ],
    'emits' => [
        'review.requested',
        'review.received',
        'reply.published',
        'csat.requested',
    ],
    'consumes' => [
        'capability.decided',
        'job.completed',
        'payment.captured',
        'ticket.resolved',
        'gbp.suspended',
        'message.received',
    ],

    // ⛔ P-163 — @owns_table may not name one of X-121's canonical nouns.
    'owns_table' => [
        'review_requests',
        'review_replies',
        'qa_settings',
    ],
    'reads_table' => [
        'reviews',
        'people',
        'qa_tickets',
    ],

    'renders' => [
        'reviews_qa_requests',
        'qa_report',
        'tickets',
        'loss_alerts',
    ],

    // P-209 — silence fails OPEN. `none` is a decision; absence is not.
    'agent_reachable' => [
        'none',
        'none',
        'none',
    ],
];
