<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 25 capability(ies) for X-200.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-200/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'G2-09' => 'qa_scorecards; an AI seat is scored exactly like a human · refuses: to score an AI seat differently from a human seat',

    // status: SPECCED
    'G2-26' => 'the wallboard (an X-194 view of live queue state)',

    // status: SPECCED
    'G2-35' => 'the wallboard;  §150.4\'s scorecard is positive only',

    // status: SPECCED
    'G2-37' => 'the wallboard',

    // status: SPECCED
    'G3-04' => 'predictive pacing under the 3% abandonment ceiling (§160.1)',

    // status: SPECCED
    'G5-09' => 'coaching on the desk; the voice is X-197\'s  ·  REFUSES with BAD_STATE',

    // status: SPECCED
    'G5-40' => 'the QA scorecard',

    // status: SPECCED
    'G9-01' => 'objection roll-up from the QA scorecards; rendered by X-194',

    // status: SPECCED
    'G9-38' => 'the wallboard',

    // status: SPECCED
    'G10-03' => 'hard maximum 3%, lower only; the UI and API reject higher (§160.1)',

    // status: SPECCED
    'G11-25' => 'named in the header — a closed set per campaign  ·  REFUSES with BAD_STATE',

    // status: SPECCED
    'G13-02' => 'the wallboard;  team-level operational state only — T677 bars the punitive read',

    // status: SPECCED
    'G16-11' => 'the coaching library — positive examples (T677)',

    // status: SPECCED
    'G16-15' => 'the wallboard — positive by construction, which is what §150.4 asks for',

    // status: SPECCED
    'G18-01' => '§18C.4 —  uncertain → treat as human, never drop a voicemail on a live person',

    // status: SPECCED
    'G18-02' => 'T677 — the fix, stated as a next action; never a ranking',

    // status: SPECCED
    'G18-03' => 'the agent desktop shows the record; the thread is X-01\'s',

    // status: SPECCED
    'G18-06' => 'a wellbeing prompt on the desk — the positive side of §150.4',

    // status: SPECCED
    'G18-08' => 'listen · whisper · barge on the seat  ·  REFUSES with BAD_STATE',

    // status: SPECCED
    'G18-13' => 'T677 — feedback to the rep, not a scoreboard against them · refuses: to act as a scoreboard against the rep — it is feedback (T677)',

    // status: SPECCED
    'G18-15' => 'live queue state; the AI answers first (R11/R20)',

    // status: SPECCED
    'G18-16' => 'T677 — a coaching signal only',

    // status: SPECCED
    'G18-19' => 'Twilio is corpus vocabulary — Infobip primary (§120–§122) · refuses: to treat Twilio as primary — Infobip is primary (§120–§122)',

    // status: SPECCED
    'G21-13' => 'a closed deal on the wallboard and in the channel  ·  REFUSES with BAD_STATE',

    // status: SPECCED
    'G15-29' => '',
];
