<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 29 capability(ies) for X-111.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-111/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'G1-29' => 'refuses: MRR blends booked with collected; booked and COLLECTED are asserted distinct (§192)',

    // status: SPECCED
    'G1-35' => 'refuses: MRR blends booked with collected; booked and COLLECTED are asserted distinct (§192)',

    // status: SPECCED
    'G2-63' => 'support tickets, by presence',

    // status: SPECCED
    'G4-05' => 'named in the header',

    // status: SPECCED
    'G4-14' => 'the operator\'s; the tenant\'s conversational search is X-01\'s.  ElasticSearch is corpus vocabulary — one database (§22)',

    // status: SPECCED
    'G4-24' => 'throttling and hard limits;  the $99/$999 tiers are dead — two packages (P-001)',

    // status: SPECCED
    'G4-28' => 'named in the header',

    // status: SPECCED
    'G4-31' => 'the screen; the mechanism is X-123\'s',

    // status: SPECCED
    'G4-33' => 'named in the header',

    // status: SPECCED
    'G4-36' => 'the auto-healing supervisor',

    // status: SPECCED
    'G4-40' => 'ops.ban plus a mass token.revoke through X-142',

    // status: SPECCED
    'G4-41' => 'the T443 delete-list runner',

    // status: SPECCED
    'G4-47' => 'SOP edit history; the same home as G1-29 Interactive SOPs',

    // status: SPECCED
    'G5-17' => 'a resolved ticket drafts a help row;  the help registry generates itself from X-122',

    // status: SPECCED
    'G5-18' => 'the HELP path; reply HUMAN always escalates (R37)',

    // status: SPECCED
    'G5-38' => 'ticket categorisation',

    // status: SPECCED
    'G7-33' => 'a spend ceiling ALERTS; it never stops the phone answering (P-095)',

    // status: SPECCED
    'G9-05' => 'named in the header; the export row is X-122\'s log',

    // status: SPECCED
    'G9-06' => '§44 · P-128 — pausing a campaign on a CPC spike is ad management',

    // status: SPECCED
    'G9-19' => 'failed searches open a help topic;  the help registry generates itself from X-122',

    // status: SPECCED
    'G9-20' => 'fleet-wide operator roll-up',

    // status: SPECCED
    'G9-28' => 'API traffic per endpoint',

    // status: SPECCED
    'G17-07' => 'ip_bans with a TTL is named in the header',

    // status: SPECCED
    'G17-17' => 'fraud velocity is named in the header',

    // status: SPECCED
    'G19-09' => 'a compromise halt is a SECURITY stop and is not the credit cap — P-095 still holds: nothing stops because a balance hit zero',

    // status: SPECCED
    'G21-02' => 'fuzzy-merged tickets; one Person, one Conversation (P-163)',

    // status: SPECCED
    'G21-05' => 'sla_due_at with escalation; every alert names an ACTION, never a fact',

    // status: SPECCED
    'G21-14' => 'the help card offered before the ticket is submitted',

    // status: SPECCED
    'G15-28' => 'reclaimed 2026-08-27 · ⛔ register description STRIPPED (P-206) — it lives in the register, not in the file the brief reads · ⑤ R188 — roles not wages; doctor asserts no pay field',
];
