<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by \`module:scaffold\` from the documented header. DO NOT EDIT.
 *
 * A hand-edited manifest is a manifest that drifts, and every stale-record
 * defect in this programme was a hand-maintained file. Change the header,
 * re-run the scaffold.
 *
 * @module X-111
 *
 * @intent INFORM under §227.2
 *
 * @ingress help.human_requested <human>
 */
return [
    'module' => 'X-111',
    'intent' => 'INFORM under §227.2',

    // ⛔⛔⛔ R235 — `ships` EQUALS `ceiling`. THE AUTOPILOT IS ON.
    //
    // This comment used to teach §227.2's intent default: "GROW ships
    // L1, PROPOSES ONLY, ALWAYS". The owner struck it — "ALL AI ON, by
    // my law. The client can turn it off if they want."
    //
    // ⭐ There is nothing to earn. @intent still DESCRIBES the action;
    //   it no longer gates when the action may run.
    'ships' => 'L3',
    'ceiling' => 'L3',

    'provides' => [
        'ops.alert',
        'ops.ticket',
        'ops.ban',
        'ops.export',
        'ops.impersonate',
    ],
    'emits' => [
        'alert.operator',
        'anomaly.detected',
        'health.degraded',
        'ticket.opened',
    ],
    'consumes' => [
        'quota.exhausted',
        'help.human_requested',
        'price.refusal_flagged',
    ],

    // ⛔ P-163 — @owns_table may not name one of X-121's canonical nouns.
    'owns_table' => [
        'operator_alerts',
        'ip_bans',
        'tenant_tickets',
        'manual_queue',
    ],
    'reads_table' => [],

    'renders' => [
        'console',
    ],

    // P-209 — silence fails OPEN. `none` is a decision; absence is not.
    'agent_reachable' => [
        'none',
        'none',
        'none',
    ],
];
