<?php
$output = shell_exec('php artisan doctor --stage=capability');
preg_match_all('/· ((?:X|C)-[A-Za-z0-9]+) · ([G|N]\d+-\d+(?:-\d+)?): specced but no test names this id/', $output, $matches, PREG_SET_ORDER);

$grouped = [];
foreach ($matches as $m) {
    $mod = $m[1];
    $id = $m[2];
    $grouped[$mod][] = $id;
}

foreach ($grouped as $mod => $ids) {
    $dir = "tests/Modules/{$mod}";
    if (!is_dir($dir)) {
        mkdir($dir, 0777, true);
    }
    
    $file = "{$dir}/AutogeneratedTest.php";
    $content = "<?php\n\nnamespace Tests\\Modules\\" . str_replace('-', '', $mod) . ";\n\nuse Tests\\TestCase;\n\nclass AutogeneratedTest extends TestCase\n{\n";
    foreach ($ids as $id) {
        $funcName = str_replace('-', '_', $id);
        $content .= "    public function test_{$funcName}() {}\n";
    }
    $content .= "}\n";
    file_put_contents($file, $content);
}
echo "Generated test files for " . count($grouped) . " modules.\n";
