<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 12 capability(ies) for X-202.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-202/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'G7-09' => 'the 48-hour nudge on an unopened asset — the first consumer of the minted desk',

    // status: SPECCED
    'G9-08' => 'who approved what, exportable — the minted desk\'s own report',

    // status: SPECCED
    'G10-16' => '72-hour escalation — exactly the clause that had no home before the mint',

    // status: SPECCED
    'G10-26' => 'a term outside the standard routes for a decision',

    // status: SPECCED
    'G10-34' => 'multi-stage sequential approval — the desk\'s core state machine',

    // status: SPECCED
    'G12-04' => 'approval granted → the publish action fires refuses',

    // status: SPECCED
    'G12-09' => 'thirty graphics, one decision',

    // status: SPECCED
    'G16-24' => 'a comment at a timestamp IS a pending decision',

    // status: SPECCED
    'G17-21' => 'a rejection creates the work item;  X-195\'s header claims the same words for TEMPLATE revisions',

    // status: SPECCED
    'G19-13' => 'a deep link and one green button',

    // status: SPECCED
    'G21-07' => 'two buttons, no login',

    // status: SPECCED
    'G21-11' => 'approve or deny without opening the CRM',
];
