<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by \`module:scaffold\` from the documented header. DO NOT EDIT.
 *
 * A hand-edited manifest is a manifest that drifts, and every stale-record
 * defect in this programme was a hand-maintained file. Change the header,
 * re-run the scaffold.
 *
 * @module X-223
 * @intent GROW
         * @ingress mail.delivered <vendor>
         * @ingress mail.bounced <vendor>
 */
return [
    'module' => 'X-223',
    'intent' => 'GROW',

    // ⛔⛔⛔ R235 — `ships` EQUALS `ceiling`. THE AUTOPILOT IS ON.
    //
    // This comment used to teach §227.2's intent default: "GROW ships
    // L1, PROPOSES ONLY, ALWAYS". The owner struck it — "ALL AI ON, by
    // my law. The client can turn it off if they want."
    //
    // ⭐ There is nothing to earn. @intent still DESCRIBES the action;
    //   it no longer gates when the action may run.
    'ships' => '',
    'ceiling' => '',

    'provides' => [
        'warmup.start',
        'warmup.state',
        'warmup.halt',
    ],
    'emits' => [
        'warmup.day.recorded',
        'warmup.halted',
    ],
    'consumes' => [
        'mail.delivered',
        'mail.bounced',
        'capability.decided',
    ],

    // ⛔ P-163 — @owns_table may not name one of X-121's canonical nouns.
    'owns_table' => [
        'warmup_domains',
        'warmup_seeds',
        'warmup_days',
    ],
    'reads_table' => [],

    'renders' => [
        'warmup_per_domain',
        'seed_pool_health',
    ],

    // P-209 — silence fails OPEN. `none` is a decision; absence is not.
    'agent_reachable' => [
        'none',
        'none',
        'none',
        'warmup.state',
    ],
];
