<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 15 capability(ies) for X-123.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-123/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'G1-11' => '⑥⑦ none — it is a seam',

    // status: SPECCED
    'G1-22' => '⑥ tenant-facing on X-142 · ⑦ none',

    // status: SPECCED
    'G1-41' => '⑥⑦ inherit refuses',

    // status: SPECCED
    'G2-52' => 'the outbound payload map on the broker',

    // status: SPECCED
    'G4-10' => 'named in the header — 10 consecutive failures, tenant emailed · refuses: retrying after 10 consecutive failures',

    // status: SPECCED
    'G4-17' => 'Horizon scales on queue depth',

    // status: SPECCED
    'G4-32' => 'queue the spike, never drop it',

    // status: SPECCED
    'G4-34' => '1 · 5 · 30 min',

    // status: SPECCED
    'G4-43' => 'global retries on every outbound call refuses',

    // status: SPECCED
    'G4-48' => 'named in the header',

    // status: SPECCED
    'G4-50' => 'they ride the same catalogue; the catalogue is X-122\'s refuses',

    // status: SPECCED
    'G7-26' => 'RabbitMQ/SQS is corpus vocabulary — Horizon + Redis (§22)',

    // status: SPECCED
    'G21-06' => 'an outbound webhook destination;  the ad-fatigue trigger behind this example is FENCED (§44)',

    // status: SPECCED
    'G21-09' => 'a channel created by webhook on a project event',

    // status: SPECCED
    'G21-12' => 'a comment event pinging the right person',
];
