<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 5 capability(ies) for X-178.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-178/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'G5-08' => 'named in the header',

    // status: SPECCED
    'G5-21' => 'the design tokens; the words\' equivalent is X-154',

    // status: SPECCED
    'G6-05' => 'named in the header',

    // status: SPECCED
    'G6-21' => 'the profile builder for an unmapped niche;  it never invents a price — [fill-me] only (P-092)',

    // status: SPECCED
    'G6-31' => 'named in the header',
];
