<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 7 capability(ies) for X-177.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-177/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'G8-01' => 'named in the header — metered, on the tenant\'s own key',

    // status: SPECCED
    'G8-09' => 'claimed-status is named in the header; the prospecting use of it is X-16\'s',

    // status: SPECCED
    'G8-17' => 'named in the header — through Zernio (§156.3)',

    // status: SPECCED
    'G8-18' => 'named in the header',

    // status: SPECCED
    'G8-27' => 'named in the header;  held while gbp.suspended',

    // status: SPECCED
    'G12-11' => 'named in the header;  held while gbp.suspended.  DALL-E is corpus vocabulary — images are X-114/X-189',

    // status: SPECCED
    'G12-31' => 'named in the header',
];
