<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 4 capability(ies) for X-220.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-220/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: *asserted: every `ai_calls` row records the prompt VERSION it used.* ⛔ **REFUSES a call whose prompt has no version — "the output changed" is unanswerable without it**
    'N-220-01' => '*asserted: every `ai_calls` row records the prompt VERSION it used.* ⛔ **REFUSES a call whose prompt has no version — "the output changed" is unanswerable without it**',

    // status: *asserted: a change to a frozen prompt creates a NEW VERSION.* ⛔ **REFUSES the edit — an experiment nobody can reproduce is not a prompt**
    'N-220-02' => '*asserted: a change to a frozen prompt creates a NEW VERSION.* ⛔ **REFUSES the edit — an experiment nobody can reproduce is not a prompt**',

    // status: *asserted: `N-238-19` — a model enters PRIMARY only after passing that job class's golden set.* ⛔⛔ **REFUSES the promotion. Without this, "any model, any vendor" means ANY QUALITY, DISCOVERED IN PRODUCTION**
    'N-220-03' => '*asserted: `N-238-19` — a model enters PRIMARY only after passing that job class\'s golden set.* ⛔⛔ **REFUSES the promotion. Without this, "any model, any vendor" means ANY QUALITY, DISCOVERED IN PRODUCTION**',

    // status: *asserted: `model_requested` AND `model_served` on every eval row (`N-238-02`).* ⛔ **REFUSES a result carrying only one — a silent fallback would attribute the BACKUP's output to the PRIMARY**
    'N-220-04' => '*asserted: `model_requested` AND `model_served` on every eval row (`N-238-02`).* ⛔ **REFUSES a result carrying only one — a silent fallback would attribute the BACKUP\'s output to the PRIMARY**',
];
