<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by \`module:scaffold\` from the documented header. DO NOT EDIT.
 *
 * A hand-edited manifest is a manifest that drifts, and every stale-record
 * defect in this programme was a hand-maintained file. Change the header,
 * re-run the scaffold.
 *
 * @module X-220
 * @intent OBSERVE
 */
return [
    'module' => 'X-220',
    'intent' => 'OBSERVE',

    // ⛔⛔⛔ R235 — `ships` EQUALS `ceiling`. THE AUTOPILOT IS ON.
    //
    // This comment used to teach §227.2's intent default: "GROW ships
    // L1, PROPOSES ONLY, ALWAYS". The owner struck it — "ALL AI ON, by
    // my law. The client can turn it off if they want."
    //
    // ⭐ There is nothing to earn. @intent still DESCRIBES the action;
    //   it no longer gates when the action may run.
    'ships' => 'L3',
    'ceiling' => 'L3',

    'provides' => [
        'prompt.resolve',
        'prompt.freeze',
        'eval.run',
        'eval.compare',
    ],
    'emits' => [
        'prompt.frozen',
        'eval.completed',
        'eval.regressed',
    ],
    'consumes' => [
        'capability.decided',
        'model.resolved',
    ],

    // ⛔ P-163 — @owns_table may not name one of X-121's canonical nouns.
    'owns_table' => [
        'ai_prompts',
        'golden_sets',
    ],
    'reads_table' => [
        'ai_calls',
        'ai_models',
    ],

    'renders' => [
        'prompt_history',
        'eval_report',
    ],

    // P-209 — silence fails OPEN. `none` is a decision; absence is not.
    'agent_reachable' => [
        'prompt.resolve',
        'none',
    ],
];
