<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 8 capability(ies) for X-116.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-116/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'G6-03' => 'P-126: 200 templates 1:1 with 200 industries; 100 PROFILES are a different object, both kept',

    // status: SPECCED
    'G6-12' => 'named in the header; the agent upsells only from a grounded Fact (P-092)',

    // status: SPECCED
    'G6-23' => 'named in the header',

    // status: SPECCED
    'G6-28' => 'named in the header — EMERGENCY · QUOTE · BOOK',

    // status: SPECCED
    'G6-29' => 'the anti-generic rule: palette varies by industry and conversion data, never by seed',

    // status: SPECCED
    'G6-30' => 'the webinar funnel shape; registrants are Person rows',

    // status: SPECCED
    'G8-19' => 'a block in the local template',

    // status: SPECCED
    'G8-35' => 'city×service pages from the template engine.  the volume is not the risk, the thinness is — every page carries real local content and passes X-140\'s cannibalisation gate; spun duplicates were killed at G3-37 (Q-012)',
];
