<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 7 capability(ies) for X-66.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-66/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'G2-21' => 'the agent reads a grounded Fact; a balance is looked up or refused (P-092)',

    // status: SPECCED
    'G2-48' => 'ElevenLabs is corpus vocabulary — the stack is X-197 (§18F)',

    // status: SPECCED
    'G18-21' => 'real-time objection detection; retrieval is X-148\'s',

    // status: SPECCED
    'G18-23' => 'transcription into the one Conversation refuses',

    // status: SPECCED
    'G16-33' => '§226.4 — the legitimate USE of enrolment: confirming the caller changing their own booking · transcribed from the plan 2026-08-27 · ⛔ register description STRIPPED (P-206) — it lives in the register, not in the file the brief reads · ⑤ enrolment confirms a caller changing their OWN booking; no other use path exists',

    // status: SPECCED
    'G16-34' => '§226.4 · P-202 — the tenant\'s OWN voice only, recorded consent, AI disclosure on every message · transcribed from the plan 2026-08-27 · ⛔ register description STRIPPED (P-206) — it lives in the register, not in the file the brief reads · ⑤ the tenant OWN voice only, recorded consent; P-202 disclosure on every message, asserted per channel',

    // status: SPECCED
    'G18-28' => '§217.2 · P-202 — "PASSIVELY" STRUCK; opt-in enrolment, the voiceprint is a `secure` field · transcribed from the plan 2026-08-27 · ⛔ register description STRIPPED (P-206) — it lives in the register, not in the file the brief reads · ⑤ "PASSIVELY" IS STRUCK — doctor asserts NO passive enrolment path exists; the voiceprint is a `secure` field',
];
