<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by \`module:scaffold\` from the documented header. DO NOT EDIT.
 *
 * A hand-edited manifest is a manifest that drifts, and every stale-record
 * defect in this programme was a hand-maintained file. Change the header,
 * re-run the scaffold.
 *
 * @module X-66
 * @intent SERVE under §227.2
 */
return [
    'module' => 'X-66',
    'intent' => 'SERVE under §227.2',

    // ⛔⛔⛔ R235 — `ships` EQUALS `ceiling`. THE AUTOPILOT IS ON.
    //
    // This comment used to teach §227.2's intent default: "GROW ships
    // L1, PROPOSES ONLY, ALWAYS". The owner struck it — "ALL AI ON, by
    // my law. The client can turn it off if they want."
    //
    // ⭐ There is nothing to earn. @intent still DESCRIBES the action;
    //   it no longer gates when the action may run.
    'ships' => 'L3',
    'ceiling' => 'L3',

    'provides' => [
        'voice.answer',
        'voice.transfer',
        'voice.voicemail_transcribe',
        'voice.coach',
    ],
    'emits' => [
        'call.ringing',
        'call.missed',
        'call.answered',
        'call.completed',
        'voicemail.transcribed',
        'sentiment.negative',
    ],
    'consumes' => [
        'carrier.selected',
        'fact.invalidated',
        'pricebook.updated',
        'capability.decided',
    ],

    // ⛔ P-163 — @owns_table may not name one of X-121's canonical nouns.
    'owns_table' => [
        'call_sessions',
        'call_turns',
        'voicemails',
        'call_autopsies',
    ],
    'reads_table' => [],

    'renders' => [
        'calls',
        'livecoaching_whisper_panel',
        'customerfacing_call_itself',
        'latency_p50p95_per',
    ],

    // P-209 — silence fails OPEN. `none` is a decision; absence is not.
    'agent_reachable' => [
        'none',
        'none',
        'none',
    ],
];
