<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 22 capability(ies) for X-112.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-112/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'G2-43' => 'the client sees the agency\'s price only (§17.5)',

    // status: SPECCED
    'G2-67' => 'the agency\'s weekly client report; rendered by X-194',

    // status: SPECCED
    'G4-09' => 'named in the header; a sub-tenant may narrow, never widen',

    // status: SPECCED
    'G4-22' => 'the agency\'s client sees results without a password',

    // status: SPECCED
    'G7-02' => '§17.5 — the client sees the agency\'s price only',

    // status: SPECCED
    'G7-05' => 'named in the header',

    // status: SPECCED
    'G7-06' => 'named in the header; the log is X-122\'s',

    // status: SPECCED
    'G7-07' => 'named in the header',

    // status: SPECCED
    'G7-12' => 'named in the header (§91\'s three agency modes) refuses',

    // status: SPECCED
    'G7-13' => 'task visibility per client',

    // status: SPECCED
    'G7-19' => 'a Loom on the client dashboard; the asset is X-114\'s',

    // status: SPECCED
    'G7-27' => 'named in the header — always logged',

    // status: SPECCED
    'G7-28' => '= the row above; one spec',

    // status: SPECCED
    'G7-30' => 'gross margin per deal; the approval above a floor is X-202\'s',

    // status: SPECCED
    'G7-31' => 'named in the header;  the Twilio figures are corpus vocabulary — Infobip, rates from X-82',

    // status: SPECCED
    'G7-34' => '= Impersonation Engine; one spec',

    // status: SPECCED
    'G7-37' => 'named in the header (§91)',

    // status: SPECCED
    'G7-44' => 'named in the header',

    // status: SPECCED
    'G9-09' => 'the agency\'s Friday client report; rendered and scheduled by X-194',

    // status: SPECCED
    'G9-32' => 'client health on the agency dashboard; the score is X-08\'s',

    // status: SPECCED
    'G16-10' => 'agency announcements are named in the header;  an un-dismissible popup is not a notification class we have (P-062)',

    // status: SPECCED
    'G19-21' => 'the account manager told before the client leaves; the score is X-08\'s',
];
