<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 21 capability(ies) for C-Agent.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/C-Agent/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'G5-01' => 'named in the header; the task lands in X-01 refuses',

    // status: SPECCED
    'G5-10' => 'untrusted text is DATA, never instruction; red evals are build-failing (P-102)',

    // status: SPECCED
    'G5-15' => '= G5-31/32; one spec',

    // status: SPECCED
    'G5-19' => 'named in the header',

    // status: SPECCED
    'G5-24' => 'named in the header',

    // status: SPECCED
    'G5-31' => 'the web-chat door is X-102\'s',

    // status: SPECCED
    'G5-32' => 'the voice door is X-66\'s; = G5-31',

    // status: SPECCED
    'G5-33' => 'ONE Conversation across channels is why it works (X-121) refuses',

    // status: SPECCED
    'G5-37' => 'the takeover latch is X-01\'s (R21)',

    // status: SPECCED
    'G5-39' => 'compose-time, both directions',

    // status: SPECCED
    'G5-41' => 'named in the header refuses',

    // status: SPECCED
    'G5-42' => 'the research behind it is X-135\'s',

    // status: SPECCED
    'G5-43' => 'the 100 authored profiles are the fixture (P-126)',

    // status: SPECCED
    'G5-48' => 'named in the header refuses',

    // status: SPECCED
    'G5-51' => 'named in the header; the minute-by-minute graph is an X-194 view',

    // status: SPECCED
    'G5-53' => 'STOP belongs to ConsentService, never the classifier (P-060)',

    // status: SPECCED
    'G10-08' => 'compose-time moderation;  Law 122 — the switch, never the rule',

    // status: SPECCED
    'G10-13' => 'compose-time only —  no LLM in the send path (P-071) refuses',

    // status: SPECCED
    'G10-19' => 'P-092 — a price is looked up or refused, never generated; a refusal without a code fails the build',

    // status: SPECCED
    'G10-37' => 'P-148 — under-18 rejected at ingest; the agent halts and hands off refuses',

    // status: SPECCED
    'G12-25' => 'negative-sentiment handoff; the takeover latch is X-01\'s (R21)',
];
