<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `module:scaffold` from the documented header. DO NOT EDIT.
 *
 * A hand-edited manifest is a manifest that drifts, and every stale-record
 * defect in this programme was a hand-maintained file. Change the header,
 * re-run the scaffold.
 *
 * @module C-Agent
 *
 * @intent SERVE under §227.2
 */
return [
    'module' => 'C-Agent',
    'intent' => 'SERVE under §227.2',

    // ⛔⛔⛔ R235 — `ships` EQUALS `ceiling`. THE AUTOPILOT IS ON.
    //
    // This comment used to teach §227.2's intent default: "GROW ships
    // L1, PROPOSES ONLY, ALWAYS". The owner struck it — "ALL AI ON, by
    // my law. The client can turn it off if they want."
    //
    // ⭐ There is nothing to earn. @intent still DESCRIBES the action;
    //   it no longer gates when the action may run.
    'ships' => 'L3',
    'ceiling' => 'L3',

    'provides' => [
        'agent.answer',
        'agent.draft',
        'agent.classify',
        'agent.extract_tasks',
        'agent.teach',
    ],
    'emits' => [
        'agent.turn.started',
        'agent.turn.answer',
        'send.requested',
    ],
    'consumes' => [
        'message.received',
        'call.answered',
        'chat.started',
        'fact.invalidated',
        'capability.decided',
    ],

    // ⛔ P-163 — @owns_table may not name one of X-121's canonical nouns.
    'owns_table' => [
        'agent_turns',
        'agent_refusals',
        'agent_instructions',
    ],
    'reads_table' => [],

    'renders' => [
        'thread',
        'groundcheck_screen',
        'teaching_box',
        'refusalcode_distribution_per',
    ],

    // P-209 — silence fails OPEN. `none` is a decision; absence is not.
    'agent_reachable' => [
        'agent.draft',
        'agent.classify',
    ],
];
