<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 11 capability(ies) for X-136.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-136/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'G3-15' => '⑥ the watch list, confirmed once · ⑦ raises, never sends',

    // status: SPECCED
    'G3-27' => 'an alert, never a send (P-068)',

    // status: SPECCED
    'G3-28' => '⑥ the watch list, confirmed once · ⑦ raises, never sends',

    // status: SPECCED
    'G3-33' => 'a 30-day re-scan raising a signal',

    // status: SPECCED
    'G3-42' => 'a signal; the alert names an action (X-111)',

    // status: SPECCED
    'G3-45' => '§44 · P-128 — geofenced ad serving is ad management refuses',

    // status: SPECCED
    'G3-56' => 'enrichment from a job posting — no scrape needed',

    // status: SPECCED
    'G4-07' => 'a new-registration signal;  a signal never mints a SendPermit (P-068) — the send is X-105\'s on Lane 3',

    // status: SPECCED
    'G7-20' => '§44 · P-128 — pre-buying geo-fenced ad inventory is ad management refuses',

    // status: SPECCED
    'G12-35' => 'a hiring signal, never a permit (P-068)',

    // status: SPECCED
    'G19-06' => 'a hiring signal, never a permit (P-068)',
];
