<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by \`module:scaffold\` from the documented header. DO NOT EDIT.
 *
 * A hand-edited manifest is a manifest that drifts, and every stale-record
 * defect in this programme was a hand-maintained file. Change the header,
 * re-run the scaffold.
 *
 * @module X-136
 *
 * @intent OBSERVE under §227.2
 */
return [
    'module' => 'X-136',
    'intent' => 'OBSERVE under §227.2',

    // ⛔⛔⛔ R235 — `ships` EQUALS `ceiling`. THE AUTOPILOT IS ON.
    //
    // This comment used to teach §227.2's intent default: "GROW ships
    // L1, PROPOSES ONLY, ALWAYS". The owner struck it — "ALL AI ON, by
    // my law. The client can turn it off if they want."
    //
    // ⭐ There is nothing to earn. @intent still DESCRIBES the action;
    //   it no longer gates when the action may run.
    'ships' => 'n/a',
    'ceiling' => 'L3',

    'provides' => [
        'signal.score',
        'signal.list',
    ],
    'emits' => [
        'signal.detected',
        'intent.high',
        'prospect.decayed',
    ],
    'consumes' => [
        'research.completed',
        'visit.started',
        'fetch.completed',
        'job.completed',
    ],

    // ⛔ P-163 — @owns_table may not name one of X-121's canonical nouns.
    'owns_table' => [
        'signals',
        'signal_scores',
        'decay_models',
    ],
    'reads_table' => [],

    'renders' => [
        'cooling',
        'signal_volume_precision',
    ],

    // P-209 — silence fails OPEN. `none` is a decision; absence is not.
    'agent_reachable' => [
        'signal.score',
        'signal.list',
        'none',
    ],
];
