<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 10 capability(ies) for X-195.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-195/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'G2-50' => 'an install is a manifest + config rows, never executable code',

    // status: SPECCED
    'G4-13' => 'flags are blast-radius control (P-182)',

    // status: SPECCED
    'G4-29' => 'an install declares its actions; the gate is the registry',

    // status: SPECCED
    'G4-49' => 'an install registers its subscriptions; the screen is X-142\'s',

    // status: SPECCED
    'G6-19' => 'named in the header',

    // status: SPECCED
    'G9-07' => 'install and usage counts for a marketplace manifest',

    // status: SPECCED
    'G19-05' => 'feature flags per tenant — blast-radius control (P-182)',

    // status: CLASSIFIED
    'G1-63' => '§226.4 — uninstall leaves ZERO orphaned subscriptions, asserted · transcribed from the plan 2026-08-27 · ⛔ register description STRIPPED (P-206) — it lives in the register, not in the file the brief reads',

    // status: SPECCED
    'G4-52' => '§226.4 — sandboxed iframe, no DOM access; a scope not in the manifest cannot be granted · transcribed from the plan 2026-08-27 · ⛔ register description STRIPPED (P-206) — it lives in the register, not in the file the brief reads · ⑤ no DOM access; a scope not in the manifest CANNOT be granted — asserted',

    // status: SPECCED
    'G4-55' => '§226.4 — a tenant-private connector, invisible cross-tenant. P-186: manifests, code NEVER · transcribed from the plan 2026-08-27 · ⛔ register description STRIPPED (P-206) — it lives in the register, not in the file the brief reads · ⑤ invisible cross-tenant, proven with two live tenants · P-186: manifests, code NEVER',
];
