<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 7 capability(ies) for X-135.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-135/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'G3-03' => 'ad intelligence; §44 fences ad management, not research',

    // status: SPECCED
    'G3-16' => 'competitor intelligence; the transcript is a Message, the weekly report an X-194 view',

    // status: SPECCED
    'G3-20' => 'research fires only on distress (P-146)',

    // status: SPECCED
    'G3-48' => 'competitor-weakness research',

    // status: SPECCED
    'G3-59' => 'every icebreaker names something TRUE (P-146)',

    // status: SPECCED
    'G5-26' => 'every cited fact carries its source and its date (P-120)',

    // status: SPECCED
    'G12-27' => 'every icebreaker names something TRUE (P-146)',
];
