<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 4 capability(ies) for X-120.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-120/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'N-046' => 'CVV IS NEVER PERSISTED, ANYWHERE, FOR ANY DURATION (P-196) — asserted against the buffer, the trace and the dump',

    // status: SPECCED
    'N-047' => 'no screen anywhere returns a decrypted PAN (P-199) — the SYSTEM has access; no PERSON does',

    // status: SPECCED
    'N-120-01' => '⛔ a grep for card-number, PAN, CVV or CVC across database/migrations returns NOTHING, enforced by CI — the only component in PCI scope proves scope by ABSENCE',

    // status: SPECCED
    'N-120-02' => 'a card expiring within 20 days raises BEFORE it fails a charge',
];
