<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 3 capability(ies) for X-217.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-217/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'N-217-01' => '⭐⭐ an accepted recruit lands in X-205 with the EXACT terms offered — offer row and program row asserted EQUAL, so a negotiated rate can never drift from what was promised',

    // status: SPECCED
    'N-217-02' => '⛔ no recruitment offer exceeds the confirmed commission ceiling',

    // status: SPECCED
    'N-217-03' => 'X-217 owns affiliate_prospects/recruitment_offers ONLY — it never writes X-205\'s affiliates/payouts tables (P-163 boundary)',
];
