<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by \`module:scaffold\` from the documented header. DO NOT EDIT.
 *
 * A hand-edited manifest is a manifest that drifts, and every stale-record
 * defect in this programme was a hand-maintained file. Change the header,
 * re-run the scaffold.
 *
 * @module X-217
 * @intent GROW
 */
return [
    'module' => 'X-217',
    'intent' => 'GROW',

    // ⛔⛔⛔ R235 — `ships` EQUALS `ceiling`. THE AUTOPILOT IS ON.
    //
    // This comment used to teach §227.2's intent default: "GROW ships
    // L1, PROPOSES ONLY, ALWAYS". The owner struck it — "ALL AI ON, by
    // my law. The client can turn it off if they want."
    //
    // ⭐ There is nothing to earn. @intent still DESCRIBES the action;
    //   it no longer gates when the action may run.
    'ships' => 'L2',
    'ceiling' => 'L2',

    'provides' => [
        'affiliate.recruit',
        'affiliate.pipeline',
        'affiliate.terms_offer',
    ],
    'emits' => [
        'none',
        'affiliate.recruited',
        'affiliate.declined',
    ],
    'consumes' => [
        'prospect.scored',
        'person.updated',
        'capability.decided',
    ],

    // ⛔ P-163 — @owns_table may not name one of X-121's canonical nouns.
    'owns_table' => [
        'affiliate_prospects',
        'recruitment_offers',
    ],
    'reads_table' => [],

    'renders' => [
        'RecruitPipeline',
        'OfferComposer',
    ],

    // P-209 — silence fails OPEN. `none` is a decision; absence is not.
    'agent_reachable' => [
        'none',
        'none',
        'none',
    ],
];
