<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 3 capability(ies) for X-119.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-119/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'G3-02' => 'the crawl is X-151\'s, the grounding store is X-119\'s.  Pinecone is corpus vocabulary — one database (§22) refuses',

    // status: SPECCED
    'G5-25' => 'the grounding law; retrieval is X-148\'s.  Pinecone is corpus vocabulary refuses',

    // status: SPECCED
    'G13-38' => 'a volunteered detail becomes a Fact with its source · refuses: an inference',
];
