<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 9 capability(ies) for X-126.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-126/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status:
    'N-049' => 'NO Fact → NO SKILL, on EVERY action, with no bypass path · a refusal always carries one of P-060\'s codes · a rate ceiling is a config ROW, never a literal ·  the gate is evaluated BEFORE the model sees the tool, not after',

    // status: SPECCED
    'N-050' => 'refuses NO_FACT',

    // status: SPECCED
    'N-051' => 'refuses NO_FACT',

    // status: SPECCED
    'N-052' => 'NO Fact → NO SKILL, on EVERY action, with no bypass path · a refusal always carries one of P-060\'s codes · a rate ceiling is a config ROW, never a literal ·  the gate is evaluated BEFORE the model sees the tool, not after',

    // status: SPECCED
    'N-054' => 'refuses NO_FACT',

    // status: SPECCED
    'N-057' => 'refuses NO_FACT',

    // status: SPECCED
    'N-060' => 'refuses NO_FACT',

    // status: SPECCED
    'N-126-01' => 'refuses NO_FACT',

    // status: SPECCED
    'N-126-02' => 'a message with valid grounding passes, and the decision is logged either way',
];
