<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 5 capability(ies) for X-189.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-189/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'G16-17' => 'the personalised overlay;  the never-fails image law — client photo → generated → branded card',

    // status: SPECCED
    'G16-18' => 'Q-012 — Google is the SEO source. The EXIF-geotag myth was settled in the corpus by citing Google\'s own engineers; injecting coordinates buys nothing and risks the profile (X-177\'s whole point)',

    // status: SPECCED
    'G16-19' => 'the branded card refuses',

    // status: SPECCED
    'G17-29' => 'the overlay engine; sourcing is X-114\'s',

    // status: SPECCED
    'G19-12' => 'the overlay engine; the SMS+MMS pair is ONE debit (R9)',
];
