<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 4 capability(ies) for X-212.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-212/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status:
    'N-038' => '500 imported jobs → ZERO outbound messages · a dry run writes NOTHING to live · one weak identifier is rejected, never merged · notes scanned to secure fields · and the EXPORT works too (P-203)',

    // status:
    'N-040' => '',

    // status:
    'N-042' => '500 imported jobs → ZERO outbound messages · a dry run writes NOTHING to live · one weak identifier is rejected, never merged · notes scanned to secure fields · and the EXPORT works too (P-203)',

    // status: SPECCED
    'G4-54' => '§217.1 — NOT an app store: one-click migration-in from ServiceTitan/Jobber/Housecall · transcribed from the plan 2026-08-27 · ⛔ register description STRIPPED (P-206) — it lives in the register, not in the file the brief reads · ⑤ P-203: the import writes rows and emits NOTHING — 500 jobs, ZERO outbound refuses',
];
