<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 6 capability(ies) for X-137.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-137/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'G3-11' => 'every visitor gets a call token;  CallTrackingMetrics is corpus vocabulary refuses',

    // status: SPECCED
    'G8-13' => 'DNI — every visitor gets a call token refuses',

    // status: SPECCED
    'G13-19' => 'the number pool — every visitor gets a call token',

    // status: SPECCED
    'G13-24' => 'a static number per offline campaign refuses',

    // status: SPECCED
    'G18-17' => 'the whisper names the SOURCE — that is what call tracking is for refuses',

    // status: SPECCED
    'G18-24' => '= Telephony Call Whisper; one spec',
];
