<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 4 capability(ies) for X-188.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-188/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'G10-02' => 'the brand is auto-submitted (P-064);  Twilio/TCR are corpus vocabulary — Infobip refuses',

    // status: SPECCED
    'G18-10' => 'the tenant\'s own registered numbers by area code refuses',

    // status: SPECCED
    'G18-11' => '= Local Caller ID; one spec.  rotation is bounded by P-065\'s per-number complaint monitoring',

    // status: SPECCED
    'G19-14' => 'P-065 makes per-number complaint monitoring mandatory under a shared brand',
];
