<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 6 capability(ies) for X-109.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-109/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'G3-06' => 'named in the header; rung ①',

    // status: SPECCED
    'G3-12' => 'P-144 — solved ONLY here, on the tenant\'s own key; a scrape that meets one retries 3× then skips',

    // status: SPECCED
    'G3-31' => 'form-field mapping',

    // status: SPECCED
    'G3-36' => 'named in the header',

    // status: SPECCED
    'G3-52' => 'personalisation is the mechanism; "defeat Akismet" is not a capability the plan can adopt without a ruling — owner question',

    // status: CLASSIFIED
    'G2-78' => 'knockout questions = form outreach refuses',
];
