<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 6 capability(ies) for X-140.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-140/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'G8-07' => 'the pre-publish gate is named in the header',

    // status: SPECCED
    'G8-24' => 'embedding similarity before publish',

    // status: SPECCED
    'G8-40' => 'named in the header',

    // status: SPECCED
    'G11-21' => 'named in the header',

    // status: SPECCED
    'G12-16' => 'named in the header;  bumping the year is not a refresh — the gate rejects a page with no new substance',

    // status: SPECCED
    'G12-21' => 'named in the header',
];
