<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 7 capability(ies) for X-122.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-122/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'G4-03' => 'every invocation logged with timestamp, IP + geo, user and actor_type',

    // status: SPECCED
    'G10-14' => 'every invocation is already immutably logged',

    // status: SPECCED
    'G10-21' => 'append-only action log;  QLDB is corpus vocabulary — one database (§22)',

    // status: SPECCED
    'G10-35' => 'HMAC-SHA256 on every outbound webhook is named in the header',

    // status: SPECCED
    'G10-41' => 'per-tenant HMAC secret on the outbound payload',

    // status: SPECCED
    'G11-26' => 'strict JSON-schema validation; a missing field is refused, never defaulted',

    // status: SPECCED
    'G17-16' => 'every invocation logs IP + MaxMind geo — named in the header',
];
