<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by \`module:scaffold\` from the documented header. DO NOT EDIT.
 *
 * A hand-edited manifest is a manifest that drifts, and every stale-record
 * defect in this programme was a hand-maintained file. Change the header,
 * re-run the scaffold.
 *
 * @module C-Mail
 *
 * @intent OBSERVE under §227.2
 */
return [
    'module' => 'C-Mail',
    'intent' => 'OBSERVE under §227.2',

    // ⛔⛔⛔ R235 — `ships` EQUALS `ceiling`. THE AUTOPILOT IS ON.
    //
    // This comment used to teach §227.2's intent default: "GROW ships
    // L1, PROPOSES ONLY, ALWAYS". The owner struck it — "ALL AI ON, by
    // my law. The client can turn it off if they want."
    //
    // ⭐ There is nothing to earn. @intent still DESCRIBES the action;
    //   it no longer gates when the action may run.
    'ships' => 'n/a',
    'ceiling' => 'L3',

    'provides' => [
        'email.send',
        'email.dns_check',
        'email.warmup',
        'email.unsubscribe',
    ],
    'emits' => [
        'email.sent',
        'email.bounced',
        'email.complained',
        'email.replied',
        'domain.warmed',
    ],
    'consumes' => [
        'campaign.scheduled',
        'notification.classified',
    ],

    // ⛔ P-163 — @owns_table may not name one of X-121's canonical nouns.
    'owns_table' => [
        'mail_domains',
        'warmup_calendars',
        'mail_events',
    ],
    'reads_table' => [],

    'renders' => [
        'dns_card',
        'sequence_view',
        'warmup_calendars_per',
        'complaintbounce_board',
    ],

    // P-209 — silence fails OPEN. `none` is a decision; absence is not.
    'agent_reachable' => [
        'none',
        'none',
        'none',
    ],
];
