<?php

namespace App\Console\DemoFill;

class Registry
{
    /**
     * @return DemoFiller[]
     */
    public static function fillers(): array
    {
        $fillers = [
            new Fillers\CAgentFiller,
            new Fillers\CAiFiller,
            new Fillers\CBillingFiller,
            new Fillers\CMailFiller,
            new Fillers\CReviewsFiller,
            new Fillers\CSmsFiller,
            new Fillers\CWhatsappFiller,
            new Fillers\X01Filler,
            new Fillers\X07Filler,
            new Fillers\X08Filler,
            new Fillers\X10Filler,
            new Fillers\X16Filler,
            new Fillers\X66Filler,
            new Fillers\X82Filler,
            new Fillers\X102Filler,
            new Fillers\X104Filler,
            new Fillers\X108Filler,
            new Fillers\X110Filler,
            new Fillers\X112Filler,
            new Fillers\X113Filler,
            new Fillers\X117Filler,
            new Fillers\X118Filler,
            new Fillers\X119Filler,
            new Fillers\X120Filler,
            new Fillers\X121Filler,
            new Fillers\X123Filler,
            new Fillers\X124Filler,
            new Fillers\X125Filler,
            new Fillers\X129Filler,
            new Fillers\X130Filler,
            new Fillers\X131Filler,
            new Fillers\X132Filler,
            new Fillers\X137Filler,
            new Fillers\X138Filler,
            new Fillers\X139Filler,
            new Fillers\X140Filler,
            new Fillers\X142Filler,
            new Fillers\X153Filler,
            new Fillers\X155Filler,
            new Fillers\X156Filler,
            new Fillers\X157Filler,
            new Fillers\X160Filler,
            new Fillers\X162Filler,
            new Fillers\X163Filler,
            new Fillers\X164Filler,
            new Fillers\X165Filler,
            new Fillers\X166Filler,
            new Fillers\X167Filler,
            new Fillers\X168Filler,
            new Fillers\X170Filler,
            new Fillers\X171Filler,
            new Fillers\X172Filler,
            new Fillers\X173Filler,
            new Fillers\X175Filler,
            new Fillers\X176Filler,
            new Fillers\X177Filler,
            new Fillers\X178Filler,
            new Fillers\X180Filler,
            new Fillers\X181Filler,
            new Fillers\X182Filler,
            new Fillers\X183Filler,
            new Fillers\X184Filler,
            new Fillers\X185Filler,
            new Fillers\X186Filler,
            new Fillers\X188Filler,
            new Fillers\X190Filler,
            new Fillers\X191Filler,
            new Fillers\X192Filler,
            new Fillers\X193Filler,
            new Fillers\X194Filler,
            new Fillers\X196Filler,
            new Fillers\X198Filler,
            new Fillers\X199Filler,
            new Fillers\X201Filler,
            new Fillers\X202Filler,
            new Fillers\X203Filler,
            new Fillers\X205Filler,
            new Fillers\X206Filler,
            new Fillers\X207Filler,
            new Fillers\X209Filler,
            new Fillers\X210Filler,
            new Fillers\X211Filler,
            new Fillers\X212Filler,
            new Fillers\X218Filler,
        ];

        usort($fillers, fn ($a, $b) => strcmp($a->module(), $b->module()));

        return $fillers;
    }
}
