<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 13 capability(ies) for X-117.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-117/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'G1-15' => 'every charge requires a fresh authorisation event — asserted by attempting a second charge on a stored token with no new consent · (P-160: tokens only) refuses',

    // status: SPECCED
    'G1-39' => 'every charge requires a fresh authorisation event — asserted by attempting a second charge on a stored token with no new consent · (P-160: tokens only) refuses',

    // status: SPECCED
    'G6-02' => 'post-charge upsell on the tokenised card (P-160 — tokens only)',

    // status: SPECCED
    'G6-07' => 'one Sellable, six fulfilment types — not mini-Shopify (P-166)',

    // status: SPECCED
    'G7-10' => 'bundle allocation on the Sellable',

    // status: SPECCED
    'G8-29' => '§143–§144 — minor units, integers, no floats',

    // status: SPECCED
    'G16-05' => 'P-120 — a countdown must be true. A timer that resets on refresh is a manufactured claim',

    // status: SPECCED
    'G1-73' => '§226.3 — fires only on a milestone the CUSTOMER accepted, never an internal status change · transcribed from the plan 2026-08-27 · ⛔ register description STRIPPED (P-206) — it lives in the register, not in the file the brief reads · ⑤ fires ONLY on a milestone the CUSTOMER accepted, never an internal status change — asserted',

    // status: SPECCED
    'G1-75' => '§226.3 — a pricing STRUCTURE, not a promotion · transcribed from the plan 2026-08-27 · ⛔ register description STRIPPED (P-206) — it lives in the register, not in the file the brief reads · ⑤ a pricing STRUCTURE, not a promotion; the price is looked up or REFUSED (P-092)',

    // status: SPECCED
    'G1-81' => '§226.3 · R190 — a tenant gifts their customer, not us gifting ours · transcribed from the plan 2026-08-27 · ⛔ register description STRIPPED (P-206) — it lives in the register, not in the file the brief reads · ⑤ issuer_scope=tenant (R190) — a tenant gifts their customer; doctor asserts no platform-scope path',

    // status: CLASSIFIED
    'G1-82' => '§226.3 — pause STOPS the meter, asserted on the next cycle · transcribed from the plan 2026-08-27 · ⛔ register description STRIPPED (P-206) — it lives in the register, not in the file the brief reads',

    // status: SPECCED
    'G17-31' => 'reclaimed 2026-08-27 · ⛔ register description STRIPPED (P-206) — it lives in the register, not in the file the brief reads · ⑤ R204: ONE currency — doctor asserts no conversion path; landed cost is OUT',

    // status: CLASSIFIED
    'G18-29' => 'will-call / pickup routing = commerce fulfilment refuses',
];
