<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 5 capability(ies) for X-208.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-208/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status:
    'N-017' => 'refuses: the TENANT supplies the Lob key; doctor asserts NO platform account exists for this channel',

    // status:
    'N-018' => 'refuses: Do-Not-Mail is checked AT GENERATION, not at send; because by the time it is at the post office it is already printed and paid for',

    // status:
    'N-019' => 'physical mail cannot be recalled',

    // status:
    'N-020' => 'refuses: every piece carries its promotion_id if it carries an offer; (§200 · P-201)',

    // status: SPECCED
    'N-208-01' => 'the cost is shown BEFORE approval — ⛔ mail never sends without it',
];
