<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 27 capability(ies) for C-Billing.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/C-Billing/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'G1-01' => 'X-198\'s MOCK gateway is asserted unreachable from a live tenant (G1-34) refuses',

    // status: SPECCED
    'G1-10' => 'an unreconciled cent RAISES, asserted by injecting a one-cent difference refuses',

    // status: SPECCED
    'G1-13' => 'a daily top-up ceiling, asserted by forcing repeated depletion refuses',

    // status: SPECCED
    'G1-14' => 'a daily top-up ceiling, asserted by forcing repeated depletion refuses',

    // status: SPECCED
    'G1-18' => 'INTEGER hundredths of a cent throughout (§18), asserted by summing a million operations and diffing to zero · the ledger is the source; the gateway receives period totals refuses',

    // status: SPECCED
    'G1-19' => 'P-095: the phone KEEPS ANSWERING. A lockout restricts the CONSOLE, never the front desk — asserted with a zero balance and an inbound call',

    // status: SPECCED
    'G1-20' => 'INTEGER hundredths of a cent throughout (§18), asserted by summing a million operations and diffing to zero · the ledger is the source; the gateway receives period totals refuses',

    // status: SPECCED
    'G1-28' => 'P-095: the phone KEEPS ANSWERING. A lockout restricts the CONSOLE, never the front desk — asserted with a zero balance and an inbound call',

    // status: SPECCED
    'G1-32' => 'INTEGER hundredths of a cent throughout (§18), asserted by summing a million operations and diffing to zero · the ledger is the source; the gateway receives period totals refuses',

    // status: SPECCED
    'G1-33' => 'exponential backoff with a hard attempt ceiling, asserted ·  a retry is the SAME refId; a new attempt is a new one (§201.3)',

    // status: SPECCED
    'G1-42' => 'exponential backoff with a hard attempt ceiling, asserted ·  a retry is the SAME refId; a new attempt is a new one (§201.3)',

    // status: SPECCED
    'G1-49' => 'exponential backoff with a hard attempt ceiling, asserted ·  a retry is the SAME refId; a new attempt is a new one (§201.3)',

    // status: SPECCED
    'G1-52' => '',

    // status: SPECCED
    'G1-56' => 'X-198\'s MOCK gateway is asserted unreachable from a live tenant (G1-34) refuses',

    // status: SPECCED
    'G1-57' => 'DERIVED from cent-precision ai_calls, never typed — asserted by changing a vendor rate and observing the debit move ·  typed does not survive a vendor price change; derived does',

    // status: SPECCED
    'G1-59' => 'exponential backoff with a hard attempt ceiling, asserted ·  a retry is the SAME refId; a new attempt is a new one (§201.3)',

    // status: SPECCED
    'G4-39' => '= G1-49 Smart Retries — already specced at §153',

    // status: SPECCED
    'G7-01' => '§45A — the 21-day timeline is the ONE ladder; a per-client grace is a date on it, never a second ladder',

    // status: SPECCED
    'G7-15' => 'every AI call writes cent-precision cost; retail debits derive at 8:1, never typed',

    // status: SPECCED
    'G9-31' => 'MRR saved by the one dunning ladder (§45A)',

    // status: SPECCED
    'G11-13' => '§45A — the 21-day timeline is the ONE ladder; day-10 is a BANNER, never a lockout',

    // status: SPECCED
    'G13-03' => '8:1 over cent-precision true cost, DERIVED, never typed',

    // status: SPECCED
    'G18-22' => 'the numbers are DEAD. The metering model of record: 7¢/min · 100 minutes included · top-ups $100→$100 and $300→$400 — and they live in X-82, never in a document',

    // status: SPECCED
    'G19-17' => 'the $50/5,000 figures are dead — auto top-up is universal and the amounts live in X-82 (T469–T474) refuses',

    // status: CLASSIFIED
    'G1-78' => ' refuses',

    // status: CLASSIFIED
    'G1-80' => 'Stripe/Authorize.Net metered billing sync',

    // status: SPECCED
    'G1-83' => '',
];
