<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 7 capability(ies) for X-182.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-182/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'G2-08' => 'social scheduling — spec with the social pass (turn 32)',

    // status: SPECCED
    'G12-10' => 'from the tenant\'s own engagement history refuses',

    // status: SPECCED
    'G12-12' => 'the reply threads into the Conversation (X-01); R20 — the agent takes every inbound',

    // status: SPECCED
    'G12-17' => 'tone per channel, inside X-154\'s lexicon',

    // status: SPECCED
    'G12-26' => 'a persona per channel; the lexicon still binds (X-154)',

    // status: SPECCED
    'G12-32' => 'the header\'s first line;  real job photos, never stock (P-131)',

    // status: SPECCED
    'G12-38' => 'the quote card is X-189\'s overlay; 1–3★ never reaches a public surface (P-110)',
];
