<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by \`module:scaffold\` from the documented header. DO NOT EDIT.
 *
 * A hand-edited manifest is a manifest that drifts, and every stale-record
 * defect in this programme was a hand-maintained file. Change the header,
 * re-run the scaffold.
 *
 * @module X-125
 *
 * @intent RECOVER under §227.2
 *
 * @scheduled rule.fired <minutely> @owner X-125
 */
return [
    'module' => 'X-125',
    'intent' => 'RECOVER under §227.2',

    // ⛔⛔⛔ R235 — `ships` EQUALS `ceiling`. THE AUTOPILOT IS ON.
    //
    // This comment used to teach §227.2's intent default: "GROW ships
    // L1, PROPOSES ONLY, ALWAYS". The owner struck it — "ALL AI ON, by
    // my law. The client can turn it off if they want."
    //
    // ⭐ There is nothing to earn. @intent still DESCRIBES the action;
    //   it no longer gates when the action may run.
    'ships' => 'L3',
    'ceiling' => 'L3',

    'provides' => [
        'flow.create',
        'flow.run',
        'flow.pause',
        'flow.rollback',
        'flow.explain',
        'flow.simulate',
    ],
    'emits' => [
        'flow.changed',
        'rule.changed',
    ],
    'consumes' => [
        '*',
    ],

    // ⛔ P-163 — @owns_table may not name one of X-121's canonical nouns.
    'owns_table' => [
        'flows',
        'flow_versions',
        'flow_runs',
    ],
    'reads_table' => [],

    'renders' => [
        'canvas',
        'runs',
        'flow_error_dashboard',
    ],

    // P-209 — silence fails OPEN. `none` is a decision; absence is not.
    'agent_reachable' => [
        'none',
        'none',
        'none',
    ],
];
