<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 6 capability(ies) for X-16.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-16/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'G3-10' => 'named in the header',

    // status: SPECCED
    'G3-14' => 'a distress signal, never a send permit (P-068)',

    // status: SPECCED
    'G3-35' => 'named in the header',

    // status: SPECCED
    'G3-41' => 'the storefront image as an Asset',

    // status: SPECCED
    'G7-21' => 'chains filtered out of the prospect set',

    // status: SPECCED
    'G8-31' => 'NAP audit across directories; the Places key is the tenant\'s own (T469–T474)',
];
