<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by \`module:scaffold\` from the documented header. DO NOT EDIT.
 *
 * A hand-edited manifest is a manifest that drifts, and every stale-record
 * defect in this programme was a hand-maintained file. Change the header,
 * re-run the scaffold.
 *
 * @module X-16
 *
 * @intent INFORM under §227.2
 *
 * @ingress refresh.due <clock>
 */
return [
    'module' => 'X-16',
    'intent' => 'INFORM under §227.2',

    // ⛔⛔⛔ R235 — `ships` EQUALS `ceiling`. THE AUTOPILOT IS ON.
    //
    // This comment used to teach §227.2's intent default: "GROW ships
    // L1, PROPOSES ONLY, ALWAYS". The owner struck it — "ALL AI ON, by
    // my law. The client can turn it off if they want."
    //
    // ⭐ There is nothing to earn. @intent still DESCRIBES the action;
    //   it no longer gates when the action may run.
    'ships' => 'L3',
    'ceiling' => 'L3',

    'provides' => [
        'maps.harvest',
        'maps.geogrid',
        'maps.polygon',
    ],
    'emits' => [
        'service.out_of_scope',
    ],
    'consumes' => [
        'territory.changed',
        'refresh.due',
    ],

    // ⛔ P-163 — @owns_table may not name one of X-121's canonical nouns.
    'owns_table' => [
        'places_records',
        'geo_grids',
        'service_polygons',
    ],
    'reads_table' => [],

    'renders' => [
        'geogrid_map',
        'servicearea_polygon',
        'harvest_coverage_by',
    ],

    // P-209 — silence fails OPEN. `none` is a decision; absence is not.
    'agent_reachable' => [
        'none',
        'none',
        'none',
    ],
];
