<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 10 capability(ies) for X-155.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-155/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'G2-17' => 'multi-step form logic',

    // status: SPECCED
    'G2-20' => 'forms write the twelve entities directly — no mapping screen',

    // status: SPECCED
    'G2-39' => 'named in X-103\'s and X-156\'s headers as well',

    // status: SPECCED
    'G3-64' => 'spam and bot filtering is named in the header',

    // status: SPECCED
    'G5-07' => 'describing the form is the wizard',

    // status: SPECCED
    'G5-30' => 'adaptive questions',

    // status: SPECCED
    'G11-01' => 'the abandon point, with the pixel',

    // status: SPECCED
    'G13-05' => 'spam and bot filtering is named in the header refuses',

    // status: SPECCED
    'G13-35' => 'hidden fields write straight to the entities, no staging table',

    // status: SPECCED
    'G17-12' => 'IP-versus-timezone as a bot signal',
];
