<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 16 capability(ies) for X-176.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-176/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'G3-34' => 'named in the header',

    // status: SPECCED
    'G8-02' => 'the internal linking graph is named in the header',

    // status: SPECCED
    'G8-03' => 'named in the header',

    // status: SPECCED
    'G8-04' => 'named in the header',

    // status: SPECCED
    'G8-14' => 'product schema from the pricebook, invalidated in the same commit',

    // status: SPECCED
    'G8-15' => 'Event schema from X-108\'s calendar',

    // status: SPECCED
    'G8-16' => 'named in the header',

    // status: SPECCED
    'G8-22' => 'named in the header',

    // status: SPECCED
    'G8-23' => 'named in the header',

    // status: SPECCED
    'G8-25' => 'named in the header',

    // status: SPECCED
    'G8-30' => 'nofollow on low-value internal links',

    // status: SPECCED
    'G8-32' => 'schema validated in CI with zero errors',

    // status: SPECCED
    'G8-33' => 'named in the header',

    // status: SPECCED
    'G12-03' => 'entity type inferred for schema, zero user input',

    // status: SPECCED
    'G16-25' => 'VideoObject injected on publish',

    // status: SPECCED
    'G7-48' => '§217.5 — SIXTH TITLE-LIE: schema nesting for the knowledge graph, not agency hierarchies · transcribed from the plan 2026-08-27 · ⛔ register description STRIPPED (P-206) — it lives in the register, not in the file the brief reads · ⑤ schema nesting for the knowledge graph, not agency hierarchies; validates with ZERO errors or does not render',
];
