<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 5 capability(ies) for X-206.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-206/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status:
    'N-043' => 'A CREDENTIAL IS NEVER RETURNED IN PLAINTEXT TO ANY CALLER — including its owner, including an admin, including the AI. A reveal is a named, time-boxed, logged ACTION with a UI, never a return value',

    // status: SPECCED
    'N-044' => 'a credential is scoped by OWNERSHIP — a tenant\'s key is unreachable from another tenant\'s seat, asserted cross-tenant',

    // status: SPECCED
    'N-045' => 'no credential appears in a log, a trace, an APM payload or a crash dump (P-196\'s exhaust rule, applied to keys)',

    // status: SPECCED
    'N-206-01' => '⛔⛔ a key still present in .env after wave 0\'s gate FAILS THE GATE',

    // status: SPECCED
    'N-206-02' => '⛔ **you may reveal what you OWN, never what you do not** *(§178)* — a reveal is a named, logged action carrying WHO · WHEN · WHICH KEY, and ⛔ **a secret is NEVER returned in plaintext to any caller, including its owner, including an admin, including the AI**',
];
