<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 9 capability(ies) for X-199.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-199/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'G1-05' => '',

    // status: SPECCED
    'G1-31' => '',

    // status: SPECCED
    'G1-40' => ' refuses',

    // status: SPECCED
    'G1-51' => '',

    // status: SPECCED
    'G1-60' => ' refuses',

    // status: SPECCED
    'G13-36' => 'invoice opened → the alert names an action',

    // status: SPECCED
    'G15-06' => 'this is the G1 anomaly resolved — §153 flagged it as specced but not a G1 register line; it is G15-06, and the itemised PDF is X-199\'s',

    // status: SPECCED
    'G15-07' => 'Law 122 / Q-061 · X-169\'s own boundary — we export, we do not file. Reciprocal state tax rules are not ours to encode.  The export survives',

    // status: SPECCED
    'G21-04' => 'card, invoices, seats — and R34\'s cancel in under 60 seconds belongs on the same screen',
];
