<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by \`module:scaffold\` from the documented header. DO NOT EDIT.
 *
 * A hand-edited manifest is a manifest that drifts, and every stale-record
 * defect in this programme was a hand-maintained file. Change the header,
 * re-run the scaffold.
 *
 * @module X-199
 *
 * @intent INFORM under §227.2
 *
 * @scheduled invoice.due <daily> @owner X-199
 */
return [
    'module' => 'X-199',
    'intent' => 'INFORM under §227.2',

    // ⛔⛔⛔ R235 — `ships` EQUALS `ceiling`. THE AUTOPILOT IS ON.
    //
    // This comment used to teach §227.2's intent default: "GROW ships
    // L1, PROPOSES ONLY, ALWAYS". The owner struck it — "ALL AI ON, by
    // my law. The client can turn it off if they want."
    //
    // ⭐ There is nothing to earn. @intent still DESCRIBES the action;
    //   it no longer gates when the action may run.
    'ships' => 'L3',
    'ceiling' => 'L3',

    'provides' => [
        'invoice.draft',
        'invoice.issue',
        'invoice.record_offline',
        'terms.set',
    ],
    'emits' => [
        'invoice.issued',
        'invoice.paid',
        'invoice.due',
    ],
    'consumes' => [
        'job.completed',
        'payment.captured',
        'subscription.renewed',
        'ledger.period_closed',
    ],

    // ⛔ P-163 — @owns_table may not name one of X-121's canonical nouns.
    'owns_table' => [
        'invoices',
        'invoice_lines',
        'credit_terms',
        'overflow_charges',
    ],
    'reads_table' => [],

    'renders' => [
        'money_paid_today',
        'unpaid',
        'declines',
        'invoices',
        'credits',
    ],

    // P-209 — silence fails OPEN. `none` is a decision; absence is not.
    'agent_reachable' => [
        'none',
        'none',
        'none',
    ],
];
