<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 6 capability(ies) for X-207.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-207/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status:
    'N-012' => 'refuses: Web Push · APNs · FCM from one internal contract; no carrier between us and the device',

    // status:
    'N-013' => 'refuses: a push is still a SEND; it passes X-204 and the cadence ceiling — asserted',

    // status:
    'N-014' => 'refuses: quiet hours apply; the owned channel is not an exemption',

    // status:
    'N-015' => 'an expired token retires quietly; it never counts as a delivery failure against the tenant',

    // status:
    'N-016' => 'refuses: the owner\'s three alerts arrive in MINUTES; (§199) — a review naming an employee, a RECOVER escalation, a money event',

    // status: SPECCED
    'N-207-01' => '⭐ every push origin passes ConsentService::decide with channel push; no push payload carries a secret field',
];
