<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 16 capability(ies) for X-10.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-10/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'G2-01' => 'proximity query over the polygon store; the field surface is X-171 refuses',

    // status: SPECCED
    'G2-07' => 'geocode → polygon → assign; named in the header',

    // status: SPECCED
    'G2-34' => 'named in the header',

    // status: SPECCED
    'G2-60' => 'the SLA reassignment already exists;  it re-routes work, it never ranks people (§150.4)',

    // status: SPECCED
    'G2-62' => 'named in the header',

    // status: SPECCED
    'G2-64' => 'demo bookings; conversion-based is named in the header',

    // status: SPECCED
    'G2-70' => 'named in the header',

    // status: SPECCED
    'G2-72' => 'named in the header',

    // status: SPECCED
    'G2-74' => 'a returning caller reaches the same owner; the carrier half is P-070 refuses',

    // status: SPECCED
    'G2-75' => '= G2-74; one spec',

    // status: SPECCED
    'G3-47' => 'an enrichment field used as a routing input',

    // status: SPECCED
    'G3-58' => 'named in the header',

    // status: SPECCED
    'G7-22' => 'the polygon owns the lead; territories are named in the header',

    // status: SPECCED
    'G15-03' => 'assignment by open workload — operational balancing, not scoring people',

    // status: SPECCED
    'G17-23' => 'territories drawn on a map — named in the header',

    // status: SPECCED
    'G17-25' => 'named in the header — a tech leaves, the polygon splits automatically',
];
