<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 4 capability(ies) for X-219.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-219/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: *asserted: `$ai->for(module, jobClass, slot)` returns a ROW, never a vendor string.* ⛔ **REFUSES with `NO_ASSIGNMENT` when no row exists — it does NOT fall back to a default model**
    'N-219-01' => '',

    // status: *asserted: an assignment whose PRIMARY and BACKUP share a provider FAILS the build (`N-237-03`).* ⛔ **REFUSES the write — a vendor outage takes every model it serves**
    'N-219-02' => '',

    // status: *asserted: `self_hosted = true` with a base url and no vendor key RESOLVES.* ⛔ **REFUSES any code path that assumes a commercial API**
    'N-219-03' => '',

    // status: *asserted: `deprecates_at` within 30 days RAISES (`R219`).* ⛔ **REFUSES the build when a sunset model sits in PRIMARY with no BACKUP**
    'N-219-04' => '',
];
