<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 7 capability(ies) for X-154.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-154/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'G2-40' => 'the lexicon governs every compose; R19 keeps medical out',

    // status: SPECCED
    'G3-29' => 'their words, not ours refuses',

    // status: SPECCED
    'G3-53' => 'personalisation at scale;  "mathematically impossible to filter" is not a claim we make (P-120)',

    // status: SPECCED
    'G5-36' => 'their words, not ours',

    // status: SPECCED
    'G5-47' => 'compose-time only — no LLM in the send path (P-071)',

    // status: SPECCED
    'G11-19' => 'named in the header — their words, not ours',

    // status: SPECCED
    'G12-19' => 'their words, their rules — and GSM-7 segmentation makes it a billing fact too refuses',
];
