<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 13 capability(ies) for X-138.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/X-138/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'G4-25' => 'UTM hygiene;  X-195\'s header claims the term for manifests',

    // status: SPECCED
    'G9-13' => 'attribution is a query, not a pipeline',

    // status: SPECCED
    'G9-14' => 'reading spend for attribution is not ad MANAGEMENT (§44 fences management); the connection is X-139\'s · refuses: ad management',

    // status: SPECCED
    'G9-33' => 'campaign → closed revenue',

    // status: SPECCED
    'G9-34' => 'named in the header — the flagship',

    // status: SPECCED
    'G13-04' => 'a pasted URL gets its UTM and its short link (P-072)',

    // status: SPECCED
    'G13-06' => 'attribution is a query over the action log',

    // status: SPECCED
    'G13-10' => 'the offline close mapped back to the click',

    // status: SPECCED
    'G13-16' => 'both stored; the model is a query, not a pipeline',

    // status: SPECCED
    'G13-21' => 'every link rides the short-linker; no module can send an untracked one (P-072)',

    // status: SPECCED
    'G13-23' => 'QR for print unpacks to a full UTM',

    // status: SPECCED
    'G13-33' => 'the branded short domain; P-072 puts shortLinkFor() in the base driver',

    // status: SPECCED
    'G17-24' => 'branded QR off every short link',
];
