<?php

declare(strict_types=1);

/**
 * ⛔ GENERATED by `capabilities:scaffold`. DO NOT EDIT.
 *
 * 4 capability(ies) for C-Sms.
 *
 * ⭐⭐ THESE ARE THE ASSERTIONS THE AGENT MUST SATISFY — AND MUST NOT AUTHOR.
 *
 * P-210: an agent that writes both the code and the test from the same
 * brief, in the same reading, produces code that is wrong and a test that
 * agrees — and the suite goes green. Every ⑤ below was written against a
 * failure mode by somebody who was not building this module.
 *
 * ⛔ An id here with no matching test under tests/Modules/C-Sms/ FAILS
 * THE BUILD. That is what stops an agent deleting an inconvenient one.
 *
 * ⚠️ An EMPTY assertion is a real gap, not a formality: it means the row
 * carries no refusal, and a ⑤ that only restates the ① protects nothing.
 */
return [
    // status: SPECCED
    'G3-54' => 'spinning text to evade carrier A2P filtering conflicts with P-064\'s 10DLC path — owner question refuses',

    // status: SPECCED
    'G11-32' => 'T677 (owner): the spintax half is reframed as Lexicon Personalization (X-154) — we do not evade carrier filtering. Stripping the URL on a 30007 and degrading honestly is the real mechanism (P-073) refuses',

    // status: SPECCED
    'G19-11' => 'R80 — it fires on the RING, not the carrier timeout; transactional, blocked by nothing but STOP (P-061) refuses',

    // status: SPECCED
    'G19-18' => 'every link rides the short-linker (P-072); 159-char discipline is the segment law refuses',
];
